### ISSUE TITLE
Request: Update instructions

### ISSUE THREAD

**Issue by manakill** [thinkst/opencanary#106]
I need up update my installation and am not sure about how to go about this.

Please add instructions to Readme for updating on Linux (and Raspberry Pi, if different)

**Comment by jayjb** [comment]
Hi @manakill,

When you say "update my installation", how did you install opencanary? Did you use `pip install opencanary` or did you clone the git repo and run `pip install .`?

**Comment by manakill** [comment]
I installed it over a year ago so it's hard to remember, but I'm pretty certain it was cloned first and then installed.

According to my notes I made, I never used pip to install.
-installed prerequisites 
-cloned git
-ran `python setup.py install`

**Comment by jayjb** [comment]
@manakill,

If you have the git repo cloned. You can just `git pull` the latest code, re-install (it wont override your config), and restart the `opencanaryd` process via `opencanaryd --stop` and `opencanaryd --start`
