### ISSUE TITLE
Error installing opencanary 0.5.6 under Python3

### ISSUE THREAD

**Issue by Bruce17** [thinkst/opencanary#114]
Hi,

I have trouble to install opencanary 0.5.6 using Python 3 which results in this error message:

```bash
$ pip3 install opencanary==0.5.6
ERROR: Could not find a version that satisfies the requirement opencanary==0.5.6
ERROR: No matching distribution found for opencanary==0.5.6
```

Tested it on Python v3.7, v3.8, v3.9 with pip v20.3.3

It does look like a miss configuration in the [pypi package description](https://pypi.org/pypi/opencanary/json):
```json
{
  "comment_text": "",
  "digests": {
    "md5": "158d8406bd4c595669a3eb3aa001a6da",
    "sha256": "a3f822332704d7863aa2356f69976d1c55777c1ff7baee3339abf30dc484900c"
  },
  "downloads": -1,
  "filename": "opencanary-0.5.6-py3-none-any.whl",
  "has_sig": false,
  "md5_digest": "158d8406bd4c595669a3eb3aa001a6da",
  "packagetype": "bdist_wheel",
  "python_version": "py3",
  "requires_python": "==2.7.*",
  "size": 3031248,
  "upload_time": "2020-08-05T15:37:12",
  "upload_time_iso_8601": "2020-08-05T15:37:12.090783Z",
  "url": "https://files.pythonhosted.org/packages/04/89/7cab8ee12eac0650c057025dbce94001ddbd437e9859c7b84cce082d314c/opencanary-0.5.6-py3-none-any.whl",
  "yanked": false,
  "yanked_reason": null
}
```

This looks wrong to me:
"python_version": **"py3"**,
"requires_python": **"==2.7.*"**,

Version v0.5.5 is properly configured and installable.

**Comment by jayjb** [comment]
Hi @Bruce17,

Thanks for reporting this. Ive noted it down and will take a look as soon as possible (and get back to you!)

**Comment by jayjb** [comment]
Hi @Bruce17,

Would you mid giving it a try now? I had to bump the version a couple times so maybe just try `pip install opencanary`

**Comment by Bruce17** [comment]
Looks good now. Thx :-)
