### ISSUE TITLE
Portscan issue

### ISSUE THREAD

**Issue by nodauf** [thinkst/opencanary#116]
I have tried to detect portscan with opencanary, but I have meet some issues. 

On my lab, I set up 3 machines. The attacker (A), the opencanary (B) and a legtimate client (C).
1. The machine A start a nmap against machine B
2. The scan is detected by machine B
3. During the scan of machine A the machine C try to connect to the web interface of machine B 

In the log, machine A and machine are detected as doing a port scan.

It appears limit rate is common for all IPs.

**Comment by jayjb** [comment]
Hi @nodauf,

Im not sure I fully follow. So is the issue the your opencanary is reporting a portscan when someone is actually trying to access the web interface (HTTP module)? 

Would you mind telling me how soon after the portscan on the Opencanary, did you try connect to the HTTP? When you did the nmap, did you target the Opencanary or do a full network nmap scan?

**Comment by nodauf** [comment]
Hi,

Thank you for taking the time to answer.

1. Yes
2. I nmap only the opencanary and during the nmap I try to access with another PC to the opencanary.

**Comment by jayjb** [comment]
Hi @nodauf,

For the HTTP alert, did you attempt a login? Since it only alerts on POST attempts.

**Comment by nodauf** [comment]
Hi,
No it was only with a GET attempts

**Comment by jayjb** [comment]
HTTP module will only alert on POST attempts. Im closing this issue; please re-open if you have more to comment.
