### ISSUE TITLE
Error when starting opencanary

### ISSUE THREAD

**Issue by brendan004** [thinkst/opencanary#12]
Hello all. I posted something about this yesterday but am unsure about what is wrong with the .opencanary.conf file. Basically, I removed the hpfeeds section in the logger section as advised:

    "logger": {
	"class" : "PyLogger",
	"kwargs" : {
	    "formatters": {
		"plain": {
		    "format": "%(message)s"
		}
	    },
	    "handlers": {
		"console": {
		    "class": "logging.StreamHandler",
		    "stream": "ext://sys.stdout"
		},
		"file": {
		    "class": "logging.FileHandler",
		    "filename": "/var/tmp/opencanary.log"
		},
		"syslog-unix": {
		    "class": "logging.handlers.SysLogHandler",
		    "address": ["localhost", 514],
		    "socktype": "ext://socket.SOCK_DGRAM"
		},
		"json-tcp": {
		    "class": "opencanary.logger.SocketJSONHandler",
		    "host": "127.0.0.1",
		    "port": 1514
		},
	    }
	}
    },

I then try to run it and get this:

[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Using config file: /root/.opencanary.conf
[-] Failed to decode json from /root/.opencanary.conf (Expecting property name: line 59 column 6 (char 1302))
[-] Failed to open /etc/opencanaryd/opencanary.conf for reading ([Errno 2] No such file or directory: '/etc/opencanaryd/opencanary.conf')
Error: config does not have 'logger' section

Line 59 is the second } after "port": 1514. I don't see any syntax issues, so I'm very confused. I'm also not a programmer so getting this honeypot up and running is a challenge. 

It was suggested I us JQ for testing. I'm on the online version trying to figure that out right now. If someone could let me know if there's something obvious I'm missing here, it would be greatly appreciated.

**Comment by thinkst** [comment]
Hey @brendan004,

At least one of the error is on line 58 of the config file. That line has an errant comma. It is now:
`   },`
but it should just be 
`  }`

If that alone doesn't fix it, attach your entire config file to the issue, and we can check it out.

**Comment by thinkst** [comment]
It's a pleasure - good to hear that it's now running.
