### ISSUE TITLE
Samba module not sending out Alerts

### ISSUE THREAD

**Issue by williamk12** [thinkst/opencanary#128]
Samba module is not sending out Alerts on events.  Rsyslog is configured correctly and /var/log/samba-audit.log file is recording audit events.  Opencanary was sending out alrets, but just stopped.  Tried restarting everything and still not working.  Also in the documentation the sample smb.conf file has this entry:
 full_audit:success = pread

This setting produces no log entrys.  I had to change it to:
full_audit:success = open read pread

This gives me useful log info.

Running on rasperry pi with Ubuntu 18 LTS image

**Comment by dmelczer** [comment]
I just found the OpenCanary project recently, and think it's fantastic but I'm having the exact same issue...samba-audit.log is populated but it does not appear as though opencanaryd is monitoring the file at all.

Is this something that is actively being worked on, or is this a misconfiguration on my end?

Also, the full_audit:success field only needs "open".  "read" and "pread" don't seem to matter.  The documentation definitely should be adjusted.

Thank you in advance for any insight you can provide!

-Dave

**Comment by manincharge** [comment]
I've noticed that the opencanary.conf  smb.auditfile setting by default is not the same as the log file value in smb.conf
Try verifying that it is the same in both places.  
(ubuntu 20.04)

**Comment by KMoonraiser** [comment]
> I've noticed that the opencanary.conf smb.auditfile setting by default is not the same as the log file value in smb.conf Try verifying that it is the same in both places. (ubuntu 20.04)

That's correct. They're not supposed to be the same. I have the same issue on Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-1044-raspi aarch64).

**Comment by techminds-max** [comment]
I have the same issue. I opened a thread today, (21/12/2021) since I hadn't noticed that others have had the same issue. I'm running opencanary in a Ubuntu 20.04 VM

**Comment by jayjb** [comment]
Hi @KMoonraiser, @dmelczer,

This does sound like a configuration issue. This value you find in your `opencanaryd.conf`:
```
"smb.auditfile": "/var/log/samba-audit.log",
```
should match the file that you specify in your Rsyslog configuration. (please check out the [wiki](https://github.com/thinkst/opencanary/wiki/Opencanary-and-Samba)).

The way to go about debugging this would be to check each of those files and see which one is missing logging. That will give you a hint as to what is broken inbetween.

**Comment by jayjb** [comment]
Hi @KMoonraiser, @dmelczer,

I've updated the regex and some of the samba log line handling as well as the wiki. Please pull the latest code and give it a try. I will be releasing a new version on pypi this week with all the new fixes. 

I'm closing this issue as solved for now. Please reopen if you would like to discuss further.
