### ISSUE TITLE
host.cfg

### ISSUE THREAD

**Issue by kontez** [thinkst/opencanary#13]
Hi,

I installed and configured OpenCanary to send mails to my GMail account, however, every few seconds I receive a mail with this message:
`{"dst_host": "0.0.0.0", "dst_port": 69, "local_time": "2016-04-06 15:07:37.544263", "logdata": {"FILENAME": "host.cfg", "MODE": "octet", "OPCODE": "READ"}, "logtype": 10001, "node_id": "opencanary-test-config", "src_host": "172.16.253.59", "src_port": 7700}`

I am using Raspbian on a Raspberry B+

Cheers,
Marvin

**Comment by thinkst** [comment]
This alert type indicates 172.16.253.59 is requesting 'host.cfg' from your device via TFTP. You'll need to investigate what the source is and whether the traffic is expected.

For better alert emails, we recommend using opencanary-correlator alongside opencanary. The correlator combines multiple events into a single incident and provides nicely formatted alerts.

**Comment by kontez** [comment]
Okay, thank you very much for your help :)
