### ISSUE TITLE
Any connection regardless of port being logged

### ISSUE THREAD

**Issue by Taomyn** [thinkst/opencanary#149]
I'm trying to get OpenCanary to work on a clean install of Debian 11 (without GUI), which after installation did not have iptables installed - no idea why, but it seems to miss a lot out when installed this way. I only noticed this because the first run of OpenCanary threw up some messages about iptable commands being incorrect but seemed to continue.

After installing iptables I still got the same messages but since then they have gone, however iptables remains devoid of any custom rules and I also see alerts for any inbound connection and not just the services I have enabled e.g. the real SSH service when connected to causes an alert.

I can't get the errors to re-appear so I'm stuck at being able to show them to you - is there as simple way to revert the install back to fresh without deleting the current enviroment?

**Comment by Taomyn** [comment]
I managed to find one of the iptables commands that fails:

```
(env) root@frink:~# /sbin/iptables -t mangle -D PREROUTING -p tcp -i lo -j LOG --log-level=warning --log-prefix=canaryfw:  -m limit --limit=3/hour
iptables: Bad rule (does a matching rule exist in that chain?).

```

**Comment by Taomyn** [comment]
Ok, so being a bit new to Debian I learnt that it now uses nftables by default - after uninstalling that, cleaning iptables and then deleting the env folder, I reinstalled opencanary and this time no errors. I do now see a PREROUTING rule but iptables shows no other.

So the original problem still remains that all connections are being alerted and not just the ones that opencanary is meant to be monitoring.

**Comment by Taomyn** [comment]
FYI, have given up on Debian 11, didn't like it as a server OS for various reasons, so have gone back to Fedora Server 34, but that had its own issues even though in the end its working better like before.

The server version of Fedora 34 needs a few more packages installing before opencanary will install: gcc, g++ and that excludes the ones where the names are slightly different i.e. python3-devel, openssl-devel, libpcap-devel, or not needed i.e. python3-venv (not found). I think that's all of them as I didn't keep track.

**Comment by jayjb** [comment]
Hi @Taomyn,

Thanks for keeping me in the loop. We actually discussing currently a best approach for opencanary deployment on different platforms since folks are using an array of different operating systems. Its hard to keep track and keep up to date all the different OS setup steps.

**Comment by jayjb** [comment]
Thank you @Taomyn for the insights. I'm closing this issue.
