### ISSUE TITLE
New install - start error

### ISSUE THREAD

**Issue by zrogers911** [thinkst/opencanary#15]
Hello, 
I have a fresh install of opencanary running on Ubuntu 14.04. I attached a screen shot of the error when I run `opencanaryd --start`. Do you have any suggestions on where to look to correct this issue?

![2016-04-26_12-48-55](https://cloud.githubusercontent.com/assets/1282712/14828609/52f0036e-0bad-11e6-9070-d1435496e583.png)

**Comment by quimmontal** [comment]
https://github.com/thinkst/opencanary/issues/9 related, can get closed

**Comment by thinkst** [comment]
This should be fixed in 2f671ea. Please check that you've created a new config from the latest default. The previous default config included a default logging option which required a non-essential dependency to be installed.

If not, please re-open a ticket and post with config file you're using.
