### ISSUE TITLE
Can't import RDP.

### ISSUE THREAD

**Issue by wlx-33** [thinkst/opencanary#153]
When I get start, here comes a error:
[-] Using config file: opencanary.conf
Can't import RDP. Please ensure you have RDP installed.
{"dst_host": "", "dst_port": -1, "local_time": "2021-08-29 08:25:02.483895", "local_time_adjusted": "2021-08-29 01:25:02.483916", "logdata": {"msg": {"logdata": "Added service from class CanaryFTP in opencanary.modules.ftp to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1, "utc_time": "2021-08-29 08:25:02.483910"}
{"dst_host": "", "dst_port": -1, "local_time": "2021-08-29 08:25:02.484130", "local_time_adjusted": "2021-08-29 01:25:02.484142", "logdata": {"msg": {"logdata": "Canary running!!!"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1, "utc_time": "2021-08-29 08:25:02.484139"}

Here is my conf:
{
	    "device.node_id": "opencanary-1",
	    "ip.ignorelist": [  ],
	    "git.enabled": false,
	    "git.port" : 9418,
	    "ftp.enabled": true,
	    "ftp.port": 21,
	    "ftp.banner": "FTP server ready",
	    "http.banner": "Apache/2.2.22 (Ubuntu)",
	    "http.enabled": false,
	    "http.port": 80,
	    "http.skin": "nasLogin",
	    "httpproxy.enabled" : false,
	    "httpproxy.port": 8080,
	    "httpproxy.skin": "squid",
	    "logger": {
		"class": "PyLogger",
		"kwargs": {
		    "formatters": {
		        "plain": {
		            "format": "%(message)s"
		        },
		        "syslog_rfc": {
		            "format": "opencanaryd[%(process)-5s:%(thread)d]: %(name)s %(levelname)-5s %(message)s"
		        }
		    },
		    "handlers": {
		        "console": {
		            "class": "logging.StreamHandler",
		            "stream": "ext://sys.stdout"
		        },
		        "file": {
		            "class": "logging.FileHandler",
		            "filename": "/var/tmp/opencanary.log"
		        }
		    }
		}
	    },
	    "portscan.enabled": false,
	    "portscan.logfile":"/var/log/kern.log",
	    "portscan.synrate": 5,
	    "portscan.nmaposrate": 5,
	    "portscan.lorate": 3,
	    "smb.auditfile": "/var/log/samba-audit.log",
	    "smb.enabled": false,
	    "mysql.enabled": false,
	    "mysql.port": 3306,
	    "mysql.banner": "5.5.43-0ubuntu0.14.04.1",
	    "ssh.enabled": false,
	    "ssh.port": 22,
	    "ssh.version": "SSH-2.0-OpenSSH_5.1p1 Debian-4",
	    "redis.enabled": false,
	    "redis.port": 6379,
	    "rdp.enabled": false,
	    "rdp.port": 3389,
	    "sip.enabled": false,
	    "sip.port": 5060,
	    "snmp.enabled": false,
	    "snmp.port": 161,
	    "ntp.enabled": false,
	    "ntp.port": 123,
	    "tftp.enabled": false,
	    "tftp.port": 69,
	    "tcpbanner.maxnum":10,
	    "tcpbanner.enabled": false,
	    "tcpbanner_1.enabled": false,
	    "tcpbanner_1.port": 8001,
	    "tcpbanner_1.datareceivedbanner": "",
	    "tcpbanner_1.initbanner": "",
	    "tcpbanner_1.alertstring.enabled": false,
	    "tcpbanner_1.alertstring": "",
	    "tcpbanner_1.keep_alive.enabled": false,
	    "tcpbanner_1.keep_alive_secret": "",
	    "tcpbanner_1.keep_alive_probes": 11,
	    "tcpbanner_1.keep_alive_interval":300,
	    "tcpbanner_1.keep_alive_idle": 300,
	    "telnet.enabled": false,
	    "telnet.port": 23,
	    "telnet.banner": "",
	    "telnet.honeycreds": [
		{
		    "username": "admin",
		    "password": "$pbkdf2-sha512$19000$bG1NaY3xvjdGyBlj7N37Xw$dGrmBqqWa1okTCpN3QEmeo9j5DuV2u1EuVFD8Di0GxNiM64To5O/Y66f7UASvnQr8.LCzqTm6awC8Kj/aGKvwA"
		},
		{
		    "username": "admin",
		    "password": "admin1"
		}
	    ],
	    "mssql.enabled": false,
	    "mssql.version": "2012",
	    "mssql.port":1433,
	    "vnc.enabled": false,
	    "vnc.port":5000
}
How can I handle this problem?

**Comment by jayjb** [comment]
Hi @wlx-33,

We currently have RDP deprecated because we want to do more work on it before its ready. You can ignore that notification.
