### ISSUE TITLE
How to send email to alert?

### ISSUE THREAD

**Issue by WlX-33** [thinkst/opencanary#156]
I configured it according to the method described in the email file, but after configuration, an error was reported and the email could not be sent. So I want to know how to send email.
Here is my configuration：
[..] # Services configuration
    "logger": {
    "class" : "PyLogger",
    "kwargs" : {
        "handlers": {
            "SMTP": {
                "class": "logging.handlers.SMTPHandler",
                "mailhost": ["authenticated.mail.server", 25],
                "fromaddr": "canary@qq.com",
                "toaddrs" : ["1234567890@qq.com"],
                "subject" : "OpenCanary Alert",
                "credentials" : ["1234567890", "rwadwmdsghuftdre"],
                "secure" : []
             }
         }
     }
 }

**Comment by jayjb** [comment]
Hi @wlx-33,

Do you mind telling me what the error that was reported is?

**Comment by wlx-33** [comment]
Here is the error:

** We hope you enjoy using OpenCanary. For more open source Canary goodness, head over to canarytokens.org. **
[-] Using config file: opencanary.conf
[-] Failed to decode json from opencanary.conf (Expecting ',' delimiter: line 36 column 17 (char 1116))
[-] Failed to open /home/wlx/.opencanary.conf for reading ([Errno 2] No such file or directory: '/home/wlx/.opencanary.conf')
[-] Using config file: /etc/opencanaryd/opencanary.conf
[-] Failed to decode json from /etc/opencanaryd/opencanary.conf (Expecting ',' delimiter: line 36 column 3 (char 1102))
No config file found. Please create one with "opencanaryd --copyconfig"

**Comment by jayjb** [comment]
Hi @wlx-33,

That looks like your OpenCanary config may be missing a bracket or something because the Opencanary application is failing to decode the config file. Can you paste your config file formatted please?

**Comment by benjaminchodroff** [comment]
This may be related, but I hit an issue with any mail server (Gmail, probably QQ too) that requires smtp with ssl. The secure only starts a tls encryption on an unencrypted connection. Most modern mail servers requires TLS handshakes, but the out of the box handler will simply timeout on the handshake. We would need to code change to support an option to use:
https://docs.python.org/3/library/smtplib.html#smtplib.SMTP_SSL
