### ISSUE TITLE
Type in Wiki, please clarify

### ISSUE THREAD

**Issue by manincharge** [thinkst/opencanary#157]
In this recently updated document, the smb.conf  log file is set to log.all  
but rsyslog.conf and opencanary.conf  are showing  samba-audit.log  

Can you explain the discrepancy or is one or more of those an error ?

https://github-wiki-see.page/m/thinkst/opencanary/wiki/Opencanary-and-Samba

**Comment by jayjb** [comment]
Hi @manincharge,

Ye so the difference there is intended.

The `samba-audit.log` is used by the OpenCanary process to read specific events forward to that log by the Rsyslog daemon. 

The `log file = log.all` reference in the `smb.conf` tells the Samba process where it should be logging to. If you check `/var/log/samba/`, you will notice that logging in there. 

The difference here is that we use the Samba module (`vfs object = full_audit`) to monitor a small selection of events that it will generate. Namely, `pread_recv pread_send` events. These are the events forward by Rsyslog to our OpenCanary monitored log file, `samba-audit.log`.

Please let me know if this helps

**Comment by manincharge** [comment]
Great,  I see properly formatted messages in the /var/log/samba-audit.log   but it isn't triggering anything in /var/tmp/opencanary.log     much less making it to the correlator.   FTP, SNMP and other types are working fine.   Any idea how to troubleshoot samba-audit.log entries  that opencanary isn't seeing ?
 "smb.auditfile": "/var/log/samba-audit.log",
    "smb.enabled": true,
    "smb.filelist": ["name": "testfile1.doc", "type": "doc"},{"name": "testfile2.txt", "type": "txt"} ],

**Comment by jayjb** [comment]
Hi @manincharge,

Sorry for the delay! We have noticed an issue with the more recent Samba versions where the operations that we tell the vfs: full_audit module to log, aren't being logged (namely `pread_*`). So this is very likely the issue. 

If you would like to try changing the `smb.conf` to reflect `full_audit:success = fstat` rather and give it another shot please.
