### ISSUE TITLE
OpenCanary inside docker reports docker IP address as src_host instead of real IP address

### ISSUE THREAD

**Issue by DimosthenisK** [thinkst/opencanary#176]
Running OpenCanary inside docker leads to the wrong src_host being reported.
This is the output I see: 
![image](https://user-images.githubusercontent.com/32791127/154663226-24d5b259-3c02-43d7-82db-ee7570f32660.png)

The first message is from visiting the honeypot from my docker host, and the second one is from visiting via my mobile.

This is my docker container configuration: 
![image](https://user-images.githubusercontent.com/32791127/154663647-0b411c07-5cfb-44f7-bfff-f07812cbe4fc.png)

This could be related to the fact that I'm not using "host" as the network configuration. Switching to that ends up in OpenCanary not responding to requests.

**Comment by jayjb** [comment]
Hi @DimosthenisK,

Thats very interesting. I would expect the src_host to be an address from the docker network if you accessed it from there. 

Ill take a look and see if there is anyway to get around this. I haven't played around with the different docker networking modes and so my knowledge here is very limited.

**Comment by HybridAU** [comment]
I don't think this is related to the fact that you're not using "host" as the network configuration. 

I've set up OpenCanary in a docker container using [published ports](https://docs.docker.com/config/containers/container-networking/#published-ports) before and the src_host has been fine. 

I'm not familiar with that syntax you have used to created the docker container, I've always used `docker-compose.yml` in the past, but it looks like that's doing the exact same thing. Is it [docker-cli-js](https://www.npmjs.com/package/docker-cli-js) that you're using?

**Comment by DimosthenisK** [comment]
Hey @HybridAU , thanks for trying to help here!

I'm using [dockerode](https://github.com/apocas/dockerode) to spin up the container, as I need it to be done programmatically. It's essentially a wrapper around the docker engine API, so yeah, I'd assume it's the same as using docker-compose.

To be clear, my end goal is getting the true IP address that tried to access the honeypot. This is my current configuration:
![image](https://user-images.githubusercontent.com/32791127/156555022-fe66064f-0a84-4f3b-89ea-f20a14fd8510.png)

It works (I can access the honeypot from the host machine at localhost:800) but the reported src_host is still the internal docker IP of the host.

**Comment by jayjb** [comment]
Hi @DimosthenisK,

Thanks for reporting in. I'm hitting the same issue at the moment, i.e. Canary is reporting the docker network IP address range instead of the the actual attacker IP.

**Comment by jayjb** [comment]
Hi @DimosthenisK,

Ive written a little bit of background around this issue. It is not in the wiki (over [here](https://github.com/thinkst/opencanary/wiki#dockerised-opencanary-is-not-reporting-the-correct-ip)). 

If you would like the correct IP we recommend either running the docker OpenCanary on a linux host or running OpenCanary natively.
