### ISSUE TITLE
Failed to load application: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by konstantia86** [thinkst/opencanary#179]
10 days ago, markupsafe was upgraded to a new version and soft_unicode was removed.
I have tried downgrading the markupsafe version to the last known working version (2.0.1) with no luck.
Any advice?

**Comment by konstantia86** [comment]
After a quick investigation, the soft_unicode library was  replaced by soft_str. (https://markupsafe.palletsprojects.com/en/2.1.x/changes/)

**Comment by NoGoCodeHunter** [comment]
@konstantia86 Sorry to be so daft, but in what CONF file do I need to update it from soft_unicode to soft_str?

**Comment by jayjb** [comment]
Hi @konstantia86,

Thats super strange. The workaround I used was to downgrade using `pip install MarkupSafe==2.0.1` which works for me. 

Would you mind letting me know which version of python you using?

**Comment by HybridAU** [comment]
Just adding that this is the same bug as #177 and can also be fixed by a [pull request that updates Jinja2](https://github.com/thinkst/opencanary/pull/175/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R16) because the new version of Jinja2 doesen't `soft_unicode` anymore

**Comment by konstantia86** [comment]
> @konstantia86 Sorry to be so daft, but in what CONF file do I need to update it from soft_unicode to soft_str?

I actually don't know because I am not that familiar with the whole project structure.

**Comment by konstantia86** [comment]
> Hi @konstantia86,
> 
> Thats super strange. The workaround I used was to downgrade using `pip install MarkupSafe==2.0.1` which works for me.
> 
> Would you mind letting me know which version of python you using?

Yes, I did this too, and actually it is better to use pip install -Iv markupsafe==2.0.1, to force the installation of the specific version. However, this needs to be fixed in the code because it may cause more problems in the future, when for instance v2.0.1 will become deprecated.

**Comment by NoGoCodeHunter** [comment]
Okay, so downgrading markupsafe seems to have resolved the issue. 
Python = 3.8.10
MarkupSafe = 2.0.1

For those having an issue here is what I did in case it helps:

Once you are in in the virtual environment:
```
pip uninstall markupsafe
pip install -Iv markupsafe==2.0.1
```

Once ran, I was able to start the 'opencanaryd'. Thanks to @konstantia86  and Good Luck.

**Comment by manincharge** [comment]
You can also replace instances of soft_unicode with soft_str.  I think I only found 3-4 references in the code.

**Comment by jayjb** [comment]
Fixed in new released version as we upgraded Jinja.
