### ISSUE TITLE
[Random UDP Port] Source

### ISSUE THREAD

**Issue by redmed666** [thinkst/opencanary#19]
Hi,

During some tests, we found that an unwanted udp port is opened by opencanary

> netstat -antup | grep python
> udp        0      0 0.0.0.0:40151               0.0.0.0:*                               21907/python

With 21907 the process ID of opencanaryd.

We don't find where this bind comes from.

Is it possible to highlight the source of that? And moreover, how to disable this bind?

Thank you.

**Comment by redmed666** [comment]
Hi,

This port is simply the port opened by opencanary to talk to the syslog daemon.

**Comment by thinkst** [comment]
Thanks for tracking that down redmed666
