### ISSUE TITLE
Ports not logging

### ISSUE THREAD

**Issue by quimmontal** [thinkst/opencanary#20]
Hi,

I was testing the logging of events of the OpenCanary, checking both the file and the correlator, when I noticed that during an nmap scan, while nmap reported all the open ports, the logger only checked in the log referred to port 8022. It didn't happen the first time, but since then it haven't logged again the other ports packets activity, and happens the same with the replicas I had created. 
How I can troubleshoot this in order to know the cause? I have just configured the correlator logging apart from the installation steps. For the record, the OpenCanary is on a Debian 8 VM.

Thanks in advance and great job!

P.S. Also I noticed that the ssh failed attempts were not logged but I though the real ssh might be colliding with the fake ssh, I don't know the real issue either.

**Comment by quimmontal** [comment]
My bad, the problem was that it wasn't actually logging packets at first, just logged login attempts and sessions made by the nmap scripts, and what seems to happen is that a normal nmap detection of the service at port 8022 creates a session, adding a log for it.

Still having the fake ssh issue, though not related to the main issue.

**Comment by AMKpeacemaker** [comment]
How did you change Opencanary from logging "only login attempts" to "loging packets"  ?

**Comment by qmontal** [comment]
Hey @AMKpeacemaker, I'm afraid I haven't touch the project since then and I no longer remember anything about that :/
