### ISSUE TITLE
from OpenSSL.SSL import Error, ZeroReturnError, WantReadError

### ISSUE THREAD

**Issue by Pragathi633** [thinkst/opencanary#214]
we keep getting this error from today when we tried to build opencanary using docker image
from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
from twisted.internet import error, udp, tcp

**Comment by Pragathi633** [comment]
builtins.TypeError: deprecated() got an unexpected keyword argument 'name'
Failed to load application: deprecated() got an unexpected keyword argument 'name'

**Comment by HybridAU** [comment]
I think it must be something has updated (OpenSSL maybe?) that no longer works with with the version of cryptography we are using. 

I tried updating the [pinned version of cryptography](https://github.com/thinkst/opencanary/blob/master/setup.py#L27) in `setup.py` to the latest version `38.0.1` and then did `docker build -f Dockerfile.latest -t opencanary:master --no-cache . `  and it worked.

I haven't tested to make sure that updating cryptography doesn't break something else, but I'm working on a branch to add HTTPS so I'll do it in that branch and then create a PR

**Comment by Pragathi633** [comment]
hey @HybridAU thank you for checking.
do you have an ETA on when this will be resolved.
thank you

**Comment by HybridAU** [comment]
No ETA sorry, I will try to look at it this weekend, maybe next weekend depending on when I can find some time, and then I'll create a PR and that will need to be reviewed / approved.

**Comment by michelcrypt4d4mus** [comment]
no idea if this is relevant but maybe worth mentioning that with macOS/homebrew it is necessary to pin the OpenSSL version to 1.1 in order to build `opencanary`.  i actually opened [a pull request with some opencanary build scripts](https://github.com/thinkst/opencanary/pull/215) quite recently; you can see the version pinning in the `build_opencanary.sh` script.
