### ISSUE TITLE
Trying to create use custom html skin

### ISSUE THREAD

**Issue by Tredmond7511** [thinkst/opencanary#222]
I'm using opencanary for security onion idh. I want to use a web page from my organization and place it on the http server on my opencanary node. I found a post that walked me through how to do this. Here's what I have so far:

I copy the web page by saving page as html
Rename the page to index.html
Upload it to the node
Copy it to the skin directory
Make a new directory and copy it to said directory.
Edit the http.skin attribute on the .conf file to the name of my new directory
Restart the idh service.

I try the web page and get nothing. I'm sure I'm messing something up but I'm not sure what. Any advice would be appreciated.

**Comment by Neleus** [comment]
Please notice that all img and js files must be located at "static" template folder but in HTML code just use path without "static"!

For Example full path to image
`static/img/logo.png`

in your HTML must be just src without "static"
`<img src="static/img/logo.png" alt="Synology">`

**Comment by jayjb** [comment]
Hi @Tredmond7511,

That sounds like a cool idea and we would be happy to help. Do you perhaps have this in a branch that I can look at?

The keys here will be to ensure that your website structure is similarly setup to the http skins that are already there. To be clear, the `http` module is expecting a certain directory structure. All static resources need to be in a `static` folder (as @Neleus has mentioned).

Please let me know how we can move forward with this.
