### ISSUE TITLE
Failed to load application: deprecated() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by elschnert** [thinkst/opencanary#229]
Starting opencanary via `docker-compose` results in the given error.
It looks like the used python library versions are incompatible right now.

I managed to get the `latest` version running with some modifications, see https://github.com/thinkst/opencanary/commit/782debbfcde44577e06c192d1ac599a1bb802417

As it is more kind of a bandaid (and doesn't solve the issue for `stable`) I didn't create a PR.

**Comment by jayjb** [comment]
Hi @elschnert,

Thanks for reporting this. Ill have a look and see what is needed to get it fixed

**Comment by donadelden** [comment]
Hi, 

Do you have any updates on this? 

I have the same problem, and the proposed fix does not work for me on the latest code version.

**Comment by jayjb** [comment]
Hi @donadelden, 

I'm not hitting the issue on latest or stable for the docker. Could you give me a little more information?

**Comment by jayjb** [comment]
Closing this issue because I can't reproduce it. Please re-open the issue with reproduction steps and more details of the host OS.
