### ISSUE TITLE
Using Proxy with Slack Webhook

### ISSUE THREAD

**Issue by Neleus** [thinkst/opencanary#234]
Hello!
I'm using slack webhook in my opencanary.conf file
  
"slack":{
                "class":"opencanary.logger.SlackHandler",
                "webhook_url":"https://XXXXX/webhooks/XXXX?id=XXXXXXXX"
            }

How can I add Proxy to all events sending via SlackHandler ? Could it possible to add such option? 
Or is it possible to somehow set a proxy for all events in the configurations?
Thanks @jayjb

**Comment by jayjb** [comment]
Hey @Survial,

Sorry for the delay in my response. Would you mind explaining it a little more? Would you like to proxy the notifications via some proxy and then to slack?

**Comment by Survial** [comment]
@jayjb Yes, just want to send notifications to slack (using my own proxy).
I can use for OpenCanary service this systemd config, but it's not good idea.
```
[Service]
Environment="HTTP_PROXY=http://example.com:1234"
Environment="HTTPS_PROXY=https://example.com:1234"
```
 Better to add proxy settings to opencanary.conf, but how?
