### ISSUE TITLE
ftp logging error

### ISSUE THREAD

**Issue by hamza005** [thinkst/opencanary#24]
what is the user name and password for ftp and how can i do that?

**Comment by thinkst** [comment]
hi @hamza005, as this is an alerting honeypot, the emulation of the FTP doesn't go beyond the login. A simple login is enough to trigger an alert. It's possible to extend the FTP module further to support this, but it isn't an aim of OpenCanary to support this.

**Comment by hamza005** [comment]
Alright, I got it. Thank you for your considerations.

Regards:
Hamza Javaid
Comsats Islamabad, Pakistan
