### ISSUE TITLE
How to get modules to run with my own writing

### ISSUE THREAD

**Issue by XzsxSzsw** [thinkst/opencanary#243]
I simulated an LDAP server and used the template provided by the project, but it didn't run.
I modified the config file and the opencanary.tac file, but when I tried to start my modules, I didn't get any response, including errors.

**Comment by jayjb** [comment]
Hi @XzsxSzsw,

Thats very cool. LDAP service would be great. Would you mind sharing the code via a branch or gist?

**Comment by XzsxSzsw** [comment]
I just wrote a simple code that mocks the LDAP service, but due to my unfamiliarity with the project, and as a beginner I have a headache about not being able to debug the project.

**Comment by XzsxSzsw** [comment]
Hello I shared my code through the branch , but I failed to run successfully, please ask if there are other files that need to be modified besides opencanary.tac

**Comment by jayjb** [comment]
Hi @XzsxSzsw,

Which branch did you share the code through? I can take a look and give you some pointers so that we can make it into a PR.

**Comment by jayjb** [comment]
Hi @XzsxSzsw,

Just wanted to ping you and see if you could provide a branch or repo for me to check the code? This sounds like a very cool module
