### ISSUE TITLE
opencanary.conf - how to display "device.node_id" in "subject"

### ISSUE THREAD

**Issue by TashiDuks** [thinkst/opencanary#26]
Hi,
I am planning to configure a subject as shown below in my opencanary.conf file so that when i receive an alert I can identify from which machine the alert is being generated.
"handlers": {
                "SMTP": {
                        "class": "logging.handlers.SMTPHandler",
                        "mailhost": ["20.20.20.20", 25],
                        "fromaddr": "honeypot@xyzcompany.com",
                        "toaddrs" : ["support@xyzcompany.com"],
                        "subject" : "**Honeypot HTTP alert on $device.node_id**"

For example when I receive the mail subject should look like "Honeypot HTTP alert on WEBSERVER".

Is this possible?

Thanks

**Comment by TashiDuks** [comment]
Anyone please??

**Comment by thinkst** [comment]
hi @TashiDuks, unfortunately the logging functionality doesn't currently support dynamically generating email subject lines. If it's something you'd like to implement, we'd be very happy to accept pull requests for it.
