### ISSUE TITLE
Multiple ports per protocol?

### ISSUE THREAD

**Issue by xme** [thinkst/opencanary#27]
Hello,
I started to play with OpenCanary and I really like it.
I searched through the documentation and did not find a answer to the following question:

Is is possible to define multiple ports for a protocol?
Ex: for Telnet, I'd like to listen for incoming traffic on ports 23,2323,5679, etc...

KR,
/x

**Comment by thinkst** [comment]
Hi @xme,

Glad you've been enjoying OpenCanary. Unfortunately there isn't a straightforward for a single service to listen on multiple ports (without a fair bit of code change) at present. However, you could try running multiple instances of OpenCanary, each configured with telnet on a different port.

**Comment by backlash-code** [comment]
Would be a nice feature. An easy way to default services would be to put a router ind front an portforward extra ports for specific services.
