### ISSUE TITLE
How can I downgrade RDP. py in version 0.9.0, as I would like it to be in version 0.4 of the Python 2.7 environment?

### ISSUE THREAD

**Issue by jayjb** [thinkst/opencanary#298]
### Discussed in https://github.com/thinkst/opencanary/discussions/294

<div type='discussions-op-text'>

<sup>Originally posted by **yahui102** August 14, 2023</sup>
How can I downgrade RDP. py in version 0.9.0, as I would like it to be in version 0.4 of the Python 2.7 environment? Because rdp.py in 0.4 can record the password of the intruder's explosion, I can determine whether our password has been leaked and has been used as a dictionary I like the fact that the 0.9.0 version has upgraded to support https.py, so I am very confused. I cannot port https.py to 0.4, nor can I port rpd.py from 0.4 to 0.9.0. Please help me, what should I do</div>

**Comment by jayjb** [comment]
Hi @yahui102,

Thanks for writing in. We are not planning on supporting python2.7 anymore. It had limited our development and maintaining backwards compatibility also slowed development. Please python3.7+ so that you can use all the new features. 

The `rdp.py` in 0.4 was deprecated because it relied on a certain RDP package (`rdpy`). The current implementation of RDP is limited but it will get an update soon.

Looking at the code of the `rdp.py` in 0.4.; it doesn't look like it should be too hard to port that code (hoping that `rdpy` supports python3 nicely)

**Comment by alopezme** [comment]
I need to grab the password in the RDP connections.....

It's in the decoded_data at rdp.py ?

Thanks

**Comment by jayjb** [comment]
Hi @alopezme, 

Extracting the username and password isn't super straight forward unfortunately and our current RDP implementation is really only geared to notify you that someone is trying to RDP to your machine. Im closing this issue because we have plans to extend RDP already.
