### ISSUE TITLE
Minor shell execution vulnerability in the portscan module configuration

### ISSUE THREAD

**Issue by brf2010** [thinkst/opencanary#3]
Line 47 and 48 of portscan.py allow you to insert some shell commands using the "portscan.synrate" configuration line. For example, touching a file:

(canarytest)[bryan@dickbutt bin]$ ls /tmp
systemd-private-b606444044104f089cb407d0fd120480-ntpd.service-NFtTi0  tmux-1000
(canarytest)[bryan@dickbutt bin]$ grep portscan opencanary.conf
    "portscan.synrate": "5/second\";touch /tmp/\"",
    "portscan.enabled": true
(canarytest)[bryan@dickbutt bin]$ opencanaryd --start
[-] Using config file: opencanary.conf
{"dst_host": "", "dst_port": -1, "local_time": "2015-09-02 14:26:13.534200", "logdata": {"msg": "Loaded module portscan"}, "logtype": 1001, "node_id": "dickbutt", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2015-09-02 14:26:13.562252", "logdata": {"msg": "Start module portscan"}, "logtype": 1001, "node_id": "dickbutt", "src_host": "", "src_port": -1}
{"dst_host": "", "dst_port": -1, "local_time": "2015-09-02 14:26:13.562593", "logdata": {"msg": "Canary running!!!"}, "logtype": 1001, "node_id": "dickbutt", "src_host": "", "src_port": -1}
(canarytest)[bryan@dickbutt bin]$ ls /tmp
second  systemd-private-b606444044104f089cb407d0fd120480-ntpd.service-NFtTi0  tmux-1000

Pretty minor because someone would have to add this to a config, which probably already implies shell access, but I ran across it and thought you'd like to know.

**Comment by thinkst** [comment]
You're right on both counts that the issue exists and about it's severity. Nevertheless, it's poor form not to enforce that to be an int. Fixed in https://github.com/thinkst/opencanary/commit/6d495598b91522a9c6b454ce4ad0310eb3aef93a
