### ISSUE TITLE
Ability to customize/extend input filed names of http.skin form elements.

### ISSUE THREAD

**Issue by RVFET** [thinkst/opencanary#329]
**Is your feature request related to a problem? Please describe.**
When I create a new http skin for my opencanary instance it only accepts "username" and "password" form elements (by name) and nothing else (i.e. custom input elements with different names).

**Describe the solution you'd like**
I'd like to be able to add other input elements too, sometimes it becomes crucial to have more than just two basic input fields.

**Describe alternatives you've considered**
Added various input elements to the markup (index.html) but all got ignored and not logged.

**Additional context**
null

**Comment by jayjb** [comment]
Hi @RVFET,

Thanks for writing in with a feature request. The current implementation works purely with what our `.html` or `.js` would send through. These are mostly the expected form inputs. To extend this service to accept all inputs could certainly be done but it does require some thinking around the design before we get to the implementation.

1. is it useful to show all form inputs sent through?
2. should the inputs expected be added to the settings `.json`?

Once we have clear definition of the problem we trying to solve, we can try engineer a solution for it.
