### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by HybridAU** [thinkst/opencanary#33]
I've been [working](https://github.com/HybridAU/opencanary) on getting OpenCanary running under Python 3.  At the moment it starts running without error in Python 3 but it runs into issue #28 with the SSH module (SSH is fine with Python 2). I still have a few more modules to test but it's almost there.

I've generally made each commit very small changing only a few lines in each commit to make it clear what each change is for. Would you be happy with a pull request like that, or would you rather all changes in a single commit for Python 3 support?

**Comment by etiennemunnich** [comment]
bump

**Comment by HybridAU** [comment]
Hey @etiennemunnich I've been busy on other projects and haven't had much time to look at Python 3 support in the last few months but @jayjb has been busy in the [portpy3](https://github.com/thinkst/opencanary/tree/portpy3) branch.

**Comment by HybridAU** [comment]
I just saw you merged Python3 support. Great work @jayjb :rocket: :tada:

**Comment by jayjb** [comment]
Hi @HybridAU,

Thanks so much for all the help. I really appreciate it!

**Comment by jayjb** [comment]
Hi @etiennemunnich,

Python 3 port is merged into master. Please let me know if it works for you.
