### ISSUE TITLE
Build docker image from source

### ISSUE THREAD

**Issue by anhtn512** [thinkst/opencanary#353]
**Is your feature request related to a problem? Please describe.**
I want modify opencanary source and rebuild it to docker image => to easy to deploy

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jayjb** [comment]
Hi @anhtn512,

Thanks for getting in touch. Can you give me more details of what you looking to do? I'm not sure I follow what you asking for

**Comment by anhtn512** [comment]
HI Jay,
I want to build an image with my custom code so I create it
```
FROM python:3.10-buster

# Download cache lists and install minimal versions
RUN apt-get update && apt-get -yq install --no-install-recommends \
	# Required linux dependencies
	sudo vim build-essential libssl-dev libffi-dev python-dev libpcap-dev && \
	# Remove cache lists and clean up anything not needed to minimize image size
	apt-get autoremove -yq && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install required pip dependencies
RUN pip install scapy pcapy-ng

WORKDIR /app
COPY . .
RUN rm -rf ./dist
RUN python setup.py sdist
RUN pip install ./dist/opencanary-*.tar.gz

# Set the default application we are running
ENTRYPOINT [ "opencanaryd" ]

# Set the default arguments to be used for the entrypoint
CMD [ "--dev" ]
```

**Comment by michelcrypt4d4mus** [comment]
[these scripts](https://github.com/thinkst/opencanary/pull/293) may or may not be helpful

**Comment by jayjb** [comment]
Hi @anhtn512,

So if im understanding you correctly, you would just like some steps to follow to build the docker image from custom opencanary code instead of pulling from `pip`?

**Comment by anhtn512** [comment]
> Hi @anhtn512,
> 
> So if im understanding you correctly, you would just like some steps to follow to build the docker image from custom opencanary code instead of pulling from `pip`?

yes, that is my point
one more thing, when I restart a container to run opencanary, it immediately stops because twistd cannot run due to the twistd.pid file already exists, I suggest we add a check in the bin/opencanaryd file to make sure everything can work again properly. Normal
Can I create a pull request?

**Comment by jayjb** [comment]
Hi @anhtn512,

Sorry for the delay in a response. Please do create a PR with that check. It sounds useful. With regards, to a docker build of github current, that also sounds useful. Let me see if we can figure that out.
