### ISSUE TITLE
[BUG] Failure to install

### ISSUE THREAD

**Issue by imasofa777** [thinkst/opencanary#358]
pip install opencanary no longer works for installing in Ubuntu 24.04 LTS
It seems to be an issue with python
Tried using the --break-system-packages option and the install does proceed further but breaks again at the uninstall of Twisted

 - OS: Ubuntu 20.04LTS

**Comment by jayjb** [comment]
Hi @imasofa777,

Please would you mind supplying us with the error that you receiving?

**Comment by imasofa777** [comment]
See below for the install we were using and the output.  I did run pip install opencanary –break-system-packages as a test and it did install, however opencanary does not run.

***@***.***:/root# apt-get install python3-dev python3-pip python3-virtualenv python3-venv python3-scapy libssl-dev libpcap-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-dev is already the newest version (3.12.3-0ubuntu1).
python3-pip is already the newest version (24.0+dfsg-1ubuntu1).
python3-virtualenv is already the newest version (20.25.0+ds-2).
python3-venv is already the newest version (3.12.3-0ubuntu1).
python3-scapy is already the newest version (2.5.0+dfsg-2ubuntu1).
libssl-dev is already the newest version (3.0.13-0ubuntu3.1).
libpcap-dev is already the newest version (1.10.4-4.1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
***@***.***:/root# pip install opencanary
error: externally-managed-environment
× This environment is externally managed╰─> To install Python packages system-wide, try apt install    python3-xyz, where xyz is the package you are trying to    install.
If you wish to install a non-Debian-packaged Python package,    create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make    sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,    it may be easiest to use pipx install xyz, which will manage a    virtual environment for you.
Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for more information.
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by imasofa777** [comment]
Just an update, the install does still work if you use the virtual environment, we were just trying to avoid using that for complication reasons.  We have since changed our install methods and installs are working properly.
