### ISSUE TITLE
[BUG] Could not run example protocol or add new protocol

### ISSUE THREAD

**Issue by minhnq1618** [thinkst/opencanary#359]
**Describe the bug**
Could not run example protocol or add new protocol

**To Reproduce**
1. Edit the opencanary.tac to enable CanaryExample0 and CanaryExample1
2. Edit the opencanary.conf to have  "example0.enabled": true and "example1.enabled": true
3. Run opencanary --dev
4. Did not see the 2 protocols show up

**Expected behavior**
Should be able to see the 2 example protocol port being open

**Screenshots**
Screenshot to show opencanary.conf
![image](https://github.com/thinkst/opencanary/assets/81002476/6a713e13-6051-4539-806d-b27a2ee8fe69)

Screenshot to show opencanary.tac
![image](https://github.com/thinkst/opencanary/assets/81002476/af58a1a7-94f5-453f-836e-b709e98ae7b8)

Screenshot to show opencanaryd --dev being run
![image](https://github.com/thinkst/opencanary/assets/81002476/1d8dfd6b-fcdd-47e2-ad64-892b9c39e717)

Screenshot to show no new port being open, the default port for example0 - 8007 and example1 - 8025
![image](https://github.com/thinkst/opencanary/assets/81002476/a6929a5b-4eaf-4bca-acef-bd112ef26807)

**Desktop (please complete the following information):**
 - Linux parrot 6.5.0-13
 - opencanaryd - 0.9.3

**Additional context**
Add any other context about the problem here. Suggested additional information
- Running in virtualenv

**Comment by thinkst-francois** [comment]
Hi @minhnq1618 

Thank you for reaching out.
I quickly tested this on my side and managed to load the examples correctly.

```
2024-06-06T07:55:30+0200 [-] CanaryExample0 starting on 8007
2024-06-06T07:55:30+0200 [opencanary.modules.example0.CanaryExample0#info] Starting factory <opencanary.modules.example0.CanaryExample0 object at 0x1052d2cd0>
2024-06-06T07:55:30+0200 [-] CanaryExample1 starting on 1502
2024-06-06T07:55:30+0200 [opencanary.modules.example1.CanaryExample1#info] Starting factory <opencanary.modules.example1.CanaryExample1 object at 0x105553110>
```

Looking at the output of `opencanaryd -dev` it shows that it is using the configuration from `/etc/opencanaryd/opencanary.conf`
Could you please confirm if the two example services have been enabled in that file.
