### ISSUE TITLE
How to use this tool to generate canary tokens is completely undocumented

### ISSUE THREAD

**Issue by lmaddox** [thinkst/opencanary#364]
**Is your feature request related to a problem? Please describe.**
All available tutorials say to use canarytokens.org to generate tokens. How to batch generate tokens, preferrably offline/locally?

**Describe the solution you'd like**
Documentation

**Describe alternatives you've considered**
Either hand-rolling a solution or writing a selenium-based script.

**Additional context**

`pdf site:https://opencanary.readthedocs.io` ==> no results found
`kali linux canary token pdf how to -canarytokens.org` ==> all results say to use canary.org. I'd prefer to do it offline, since the selenium script is slow. Otherwise, I can post the script and we can see about speeding it up.

```
how to create a canary token from scratch pdf -help.canary.tools -help.canary.tools -canarytokens.org -help.canary.tools -www.hackercombat.com -vext.info -blog.thinkst.com -infosecinstitute.com -canarytokens.org -canary.tools
```

**Comment by ranok** [comment]
@lmaddox sorry the docs were unclear, if you could give us some pointers how you came across this it would be helpful. I think you are looking for the Canarytokens repository as opposed to this one, which is for a Honeypot. If you check out https://github.com/thinkst/canarytokens-docker it will allow you to spin up your own Canarytokens server so you're not reliant on Canarytokens.org.

**Comment by lmaddox** [comment]
yes, you're absolutely right. Thanks

for posterity: https://adhdproject.github.io/#!Tools/Attribution/CanaryTokens.md
