### ISSUE TITLE
[BUG] Install guide does not work with specified Ubuntu 20.04 on Raspberry Pi (ARM)

### ISSUE THREAD

**Issue by bear-goes-bleep** [thinkst/opencanary#367]
**Describe the bug**

Clarification is needed in install instructions for Ubuntu ARM, maybe X86 too. 

https://github.com/thinkst/opencanary?tab=readme-ov-file#installation-on-ubuntu states you should run **Ubuntu 20.04**. That version have python 3.8 (iirc) but requirements on ARM have at least 3.9. 

Running Ubuntu 22.04 have python 3.10.12 and the guide works perfectly. 

**To Reproduce**
1. Install Ubuntu 20.04 LTS for Raspberry Pi (in my case RPI 3b)
2. Follow Instructions for 20.04 https://github.com/thinkst/opencanary?tab=readme-ov-file#installation-on-ubuntu
3. Opencanary install fails with different errors
4. A couple of errors 
```
ERROR: Could not find a version that satisfies the requirement cryptography (from versions: none)
ERROR: No matching distribution found for cryptography
```
5. Install instead with Ubuntu 22.04 for Raspberry pi = installation works flawlessly!

**Expected behavior**
Opencanary install fails ubuntu 20.04, probably due to wrong python version

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu server 20.04 LTS (fully patched)

**Additional context**
Guide works correct if Ubuntu 22.04 is run instead of 20.04 on Raspberry Pi

**Comment by jayjb** [comment]
Hi @bear-goes-bleep, 

Thanks so much for reporting this. Would you like to create a PR with the documentation updates please? We really appreciate folks contributing/reporting these kinds of things - it was save someone a lot of time down the line.

**Comment by jayjb** [comment]
Hi @bear-goes-bleep,

Just checking in to see if you are available to help out with updating the docs and sending through a PR?

**Comment by bear-goes-bleep** [comment]
Hi @jayjb 

Sorry for inactivity! Sure, I just need to figure out how I do it, but I will surely manage! :)

**Comment by bear-goes-bleep** [comment]
Hey @jayjb 

Ok, I think I have created my very first PR ever. Let me know if it looks off or something is missing. 

https://github.com/thinkst/opencanary/pull/371

Thanks

**Comment by jayjb** [comment]
Yay, thanks @bear-goes-bleep! Thanks so much for contributing. We always appreciate the report and doubly appreciate the PR. Please can you email me at jay [at] thinkst [dot] com. We have something we would like to send you.
