### ISSUE TITLE
[BUG] Portscan module failing on startup

### ISSUE THREAD

**Issue by IHaveAGenericUserName** [thinkst/opencanary#379]
**Describe the bug**
Portscan module in virtualenv fails to start due to error in startYourEngines function.

Error Log
`
{"logdata": "Failed to run startYourEngines on CanaryPortscan in opencanary.modules.portscan. Traceback (most recent call last):\n  File \"/home/user/env/bin/opencanary.tac\", line 112, in start_mod\n    obj.startYourEngines()\n  File \"/home/user/env/lib/python3.12/site-packages/opencanary/modules/portscan.py\", line 104, in startYourEngines\n    self.set_iptables_rules()\n  File \"/home/user/env/lib/python3.12/site-packages/opencanary/modules/portscan.py\", line 120, in set_iptables_rules\n    iptables_path = self.getIptablesPath()\n                    ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/user/env/lib/python3.12/site-packages/opencanary/modules/portscan.py\", line 95, in getIptablesPath\n    if detectNFTables():\n       ^^^^^^^^^^^^^^^^\n  File \"/home/user/env/lib/python3.12/site-packages/opencanary/modules/portscan.py\", line 71, in detectNFTables\n    return b\"nf_tables\" in safe_exec(\"iptables\", [\"--version\"])\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/user/env/lib/python3.12/site-packages/opencanary/__init__.py\", line 34, in safe_exec\n    return subprocess.check_output(args, shell=True, executable=exec_path)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['--version']' returned non-zero exit status 2.\n"}}, "logtype": 1001, "node_id": "testoc", "src_host": "", "src_port": -1, "utc_time": "2024-10-17 12:28:36.028349"}
`

**To Reproduce**
Fresh virtualenv, following readme for fresh install via pip, start opencanaryd all modules load except portscan.

**Expected behavior**
Portscan module will load.

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS

**Additional context**
Add any other context about the problem here. Suggested additional information
- Installed via pip
- Running in virtualenv? yes
- Running in docker? docker version? no

**Comment by thinkst-az** [comment]
@IHaveAGenericUserName thanks for this report - we're working on a fix.

**Comment by thinkst-az** [comment]
@IHaveAGenericUserName : we've pushed a fix in v0.9.5. Updating should sort this.
