### ISSUE TITLE
SMTP auth extension not supported by server

### ISSUE THREAD

**Issue by ceveyp** [thinkst/opencanary#38]
I get this message when I run opencanaryd --start. I don't know how to fix it

**Comment by ceveyp** [comment]
ALL BECAUSE I'm missing one line of code in the conf file: "secure" : []. This is not in the documentation at all. I spent hours troubleshooting because this is very poor documentation

**Comment by thinkst** [comment]
Sorry for the pain @ceveyp. We have added it to the documentation.
