### ISSUE TITLE
[BUG] HTTP Service "Process failed"

### ISSUE THREAD

**Issue by Blu3panda-dev** [thinkst/opencanary#386]
**Describe the bug**

When I use the http service and i go to {ip}:80 it does not automatically redirect me to the index.html but instead shows the following page. the other picture is the response from opencanary in the CLI.

![image](https://github.com/user-attachments/assets/bacb121b-77ab-4685-add8-d28dfff81140)

![image](https://github.com/user-attachments/assets/aeb587d0-75ab-438f-8e21-139e722dd260)

The issue is the same whenever I have a different skin selected. When I search for {IP}:80/index.html the correct page does load . Is this a deliberate choice or not? I could not easily find how to change this without digging into the code myself. I followed this installation method :

$ sudo apt-get install python3-dev python3-pip python3-virtualenv python3-venv python3-scapy libssl-dev libpcap-dev
$ virtualenv env/
$ . env/bin/activate
$ pip install opencanary

i am running the latest version of python. The latest LTS version from ubuntu ARM based.

**Expected behavior**

I expected that it would redirect me to index.html. whenever i would visit port 80 on the IP of my Canary.

Add any other context about the problem here. Suggested additional information
- Installed via pip or installed via github: pip
- Running in virtualenv : yes
- Running in docker : no
- Services enabled or running : HTTP

**Comment by B9Security** [comment]
Panda, did you ever find a solution for that ?
