### ISSUE TITLE
logger error

### ISSUE THREAD

**Issue by deanhinson** [thinkst/opencanary#43]
I am trying to send logs to another device via tcp. The other end is receiving the logs but I get this alert:

"Dropping log message due to too many failed sends"

I am not exactly sure why, i see in the logger.py file where the error is but i cant figuer out why its happening on my device.

**Comment by thinkst** [comment]
Hey @deanhinson,

Thanks for reporting this issue. I will add it to my list and let you know what I find. 

Kind Regards

**Comment by jayjb** [comment]
Hey @deanhinson,

Im closing this issue for now. Please reopen if you would like to continue the discussion.
