### ISSUE TITLE
OpenBSD packet filter (pf) - portscan.py iptables

### ISSUE THREAD

**Issue by AMKpeacemaker** [thinkst/opencanary#44]
Hi there,

I was trying to get opencanary running on my OpenBSD, but then I realized, opencanary is using iptables and OpenBSD is using pf.

Are there any known "workarounds" or hints to change the iptables command so it'll work with OpenBSD ?

(portscan.py):
`os.system('sudo /sbin/iptables -t mangle -D PREROUTING -p tcp {dst} --syn -j LOG --log-level=warning --log-prefix="canaryfw: " -m limit --limit="{synrate}/second"'
                    .format(dst=(('--destination '+self.listen_addr) if len(self.listen_addr) else ''),
                        synrate=self.synrate))
       
 os.system('sudo /sbin/iptables -t mangle -A PREROUTING -p tcp {dst} --syn -j LOG --log-level=warning --log-prefix="canaryfw: " -m limit --limit="{synrate}/second"'
                    .format(dst=(('--destination '+self.listen_addr) if len(self.listen_addr) else ''),
                        synrate=self.synrate))`

I don't have much experience regarding this issue.

Best regards
Klara

**Comment by thinkst** [comment]
Hey @AMKpeacemaker,

Ill take a look into it and let you know about any possible workarounds. 

Kind Regards

**Comment by AMKpeacemaker** [comment]
Hi @thinkst 
thank you for looking into this issue.
I was trying myself to solve this, with creating a second logfile via "pf" and merging it back into opencanary, but I got stuck. 

PF is logging every portscan regarding the open-canary-Ports, since it's written in TCPDUMP Packet-Capture-Binary-Format, I created a little script to convert it to readable text and changed the syslog.conf . 

Converting-Binary-To-Text-Script
`#!/bin/sh

PFLOG=/var/log/pflog
FILE=/var/log/pflog2min.txt


#if file is readable and size > 24 bytes; then
if [ -r $PFLOG ] && [ $(stat -f %z $PFLOG) -gt 24 ]; then
mv $PFLOG $FILE
touch $PFLOG
#start pflogd
pflogd

#convert binary into readable file
tcpdump -n -e -ttt -r $FILE | logger -t pf -p local0.info
rm $FILE

fi`

It's rotating every 30 seconds (crontab) and works fine as far as I can tell. 
And right there I got stuck, because I am not quite sure, how to change the output into the correct format and redirecting it back into opencanary.

Best Regards
Klara

**Comment by AMKpeacemaker** [comment]
Ahoi,

I've converted the readable PCAP-File into "Opencanary-Format" with a little python-script (called within the bash-script above) and redirected it into a seperate Log-File.

Example-log-entry:
> canaryfw: Jun 21 11:23:38 IN=interface0 SRC=XXX.XXX.XXX.XXX DST=XXX.XXX.XXX.XXX LEN=44 TTL=64 ID=33450 SPT=3306 DPT=37161 WINDOW=16384

Now I was wondering where/how I can "submit" these informations back into OpenCanary.
Can I use an existing logger within the opencanary.conf ?
Do I have to involve the portscan.py file?

Best Regards
Klara

**Comment by thinkst** [comment]
Hey @AMKpeacemaker,

That is very cool (and very useful!). Thanks. If you wish, you can submit a pull request. This will allow me to check out and test the code. I would be interested in seeing how you got this working. Currently we do not support OpenBSD (nor aim to), but this is definitely a point in favour of moving towards supporting it.

**Comment by AMKpeacemaker** [comment]
Hi @thinkst ,

at first I changed the Packet-Filter-Configuration (/etc/pf.conf) by activating logging for the ports, used by Opencanary and setting an own "sync-rate" (max-src-conn-rate) like u did via iptables:

```
if="{vmx0}"

set block-policy drop
set loginterface pflog0


tcp_pass= "{80 22}"
tcp_services = "{21 23 69 3306 5060 8022}"



block in on $if proto tcp all
pass in log on $if proto tcp to port $tcp_services keep state(max-src-conn 5, max-src-conn-rate 5/1)
pass in on $if proto tcp to port $tcp_pass
pass out on $if proto tcp to port $tcp_pass
```

Then i changed the created PCAP-Binary file into "open-canary-format" with two steps:
1. A bash-script converting the PCAP-Binary format into readable text (/etc/pflogrotate):

```
#!/bin/sh

PFLOG=/var/log/pflog
FILE=/var/log/pflog2min.txt


#if file is readable and size > 24 bytes; then
if [ -r $PFLOG ] && [ $(stat -f %z $PFLOG) -gt 24 ]; then
mv $PFLOG $FILE
touch $PFLOG


#start pflog-daemon
pflogd

#convert binary into readable file and send to syslog
tcpdump -s 160 -n -ttt -e -v -r $FILE > /var/log/pflog.txt

rm $FILE

#execute python-script to convert into opencanary format
/usr/local/bin/python /etc/pflogformat.py &
wait $!

rm /var/log/pflog.txt
touch /var/log/pflog.txt


fi

```
and calling a python-script to convert the readable  text into "open-canary-format" (/etc/pflogformat.py) within the bash-script:

```
import re

#Path-Logfile
file = '/var/log/pflog.txt'
file2= '/var/log/canaryfw.log'

#Regexpression
searchstring ='(?P<date>\w+\s\S+\s\d+:\d+:\d+).+?(?=])]\spass\s\S+\son\s(?P<IN>\w+):\s(?P<SRC>\d+.\d+.\d+.\d+).(?P<SPT>\d+)\s>\s(?P<DST>\d+.\d+.\d+.\d+).(?P<DPT>\d+):\s(?P<FLG>\S+).+?(?=win)win\s(?P<WINDOW>\d+)\s.+?(?=\()\(ttl\s(?P<TTL>\d+),\sid\s(?P<ID>\d+),\slen\s(?P<LEN>\d+)'



#Open logfile
with open(file) as f:
    for line in f:
        #Search with regexpression
        result=re.search(searchstring,line)
        #Format pf -> opencanary
        if result:
            date = result.group('date')
            interface = result.group('IN')
            sourceIP = result.group('SRC')
            sourcePT = result.group('SPT')
            destIP = result.group('DST')
            destPT = result.group('DPT')
            flag = result.group('FLG')
            window = result.group('WINDOW')
            ttl = result.group('TTL')
            id = result.group('ID')
            length = result.group('LEN')

            res2 ="canaryfw: "+date+" IN="+interface+" SRC="+sourceIP+" DST="+destIP+" LEN="+length+" TTL="+ttl+" ID="+id+" SPT="+sourcePT+" DPT="+destPT+" WINDOW="+window+"\n"
            with open(file2,"a") as myfile:
                myfile.write(res2)
                myfile.close()

```

As last step, I edited crontab for root, to let the bash-script rotate for every 2 mins:
*/2     *       *       *       *       /bin/sh /etc/pflogrotate



The only thing left to do is, integrating canaryfw.log back into Opencanary.
(Still trying to figure that out :) )


Best Regards
Klara

**Comment by thinkst** [comment]
Hey @AMKpeacemaker,

Wow this is really great. Congratulations (and thanks for keeping us in the loop!). When you ready, you can open a pull request and we can give it a look over and test. 

We would also like to send you something to say thanks for the contribution. So ping us with your details and ill get on that in the meantime 👍

**Comment by MarioHarm** [comment]
Hi @thinkst ,

I created a pull-request with my other Account, since I am not really experienced with git I don't know how to send private messages regarding my details - also I dont know what informations you might need. I hope the commited code is useful regarding your project.

Best Regards
AMKpeacemaker

**Comment by thinkst** [comment]
Hey @AMKpeacemaker,

I just wanted to give you an update. We love what you have done (its really cool), but we have decided not to include it in our repo, simply because we are not aiming at supporting OpenBSD. This said, would you mind if we directed people to your repo if they are searching for OpenBSD compat OpenCanary? 

Thanks again for the great work

**Comment by AMKpeacemaker** [comment]
My pleasure, thanks for the "canary-Swag-wear"  :-) 

> would you mind if we directed people to your repo if they are searching for OpenBSD compat OpenCanary?

Sure, if somebody wants OpenCanary get to work on OpenBSD, I would be happy help out with this code.

Best  Regards
AMKpeacemaker

**Comment by gretel** [comment]
@AMKpeacemaker i think you should make a `port` out of your effort considering the author not interested in supporting `openbsd` https://www.openbsd.org/faq/ports/guide.html

**Comment by tpchikumbu** [comment]
@AMKpeacemaker I'm working on a FreeBSD port for OpenCanary and would like to use your repo as a basis for it but it doesn't seem to be available anymore. Would you mind sharing it if you still have the files?
