### ISSUE TITLE
Failed building wheel for pcapy

### ISSUE THREAD

**Issue by citnadxela** [thinkst/opencanary#45]
Trying to set up opencanary.  However, when I get to this step:

pip install scapy pcapy # optional

After running it, it seems like scapy installs fine, but pcapy always fails wi/ this error:

'Failed building wheel for pcapy'

Command "/root/env/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-aPcW_X/pcapy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Y3V2nc/install-record.txt --single-version-externally-managed --compile --install-headers /root/env/include/site/python2.7/pcapy" failed with error code 1 in /tmp/pip-install-aPcW_X/pcapy/

Would I be missing any dependencies/packages?  For the most part, I installed Python 2.7 using:

sudo apt install python-minimal

& ran:

sudo apt-get install python-dev python-pip python-virtualenv

to begin the configuration process.

**Comment by Emi94** [comment]
I got the same error. Fixed it by installing these packages:
`apt-get install libpcap-dev libpq-dev`

**Comment by flamingsnowflake** [comment]
libpcap-dev is still required as of 19 June 2021 - install on ubuntu 20.04 as per git wiki. the dependency is not listed
apt install libpcap-dev satisfies it. maybe add to wiki? as the error is very unspecific...
```

e-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c pcapdumper.cc -o build/temp.linux-x86_64-3.8/pcapdumper.o
    pcapdumper.cc:11:10: fatal error: pcap.h: No such file or directory
       11 | #include <pcap.h>
          |          ^~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------

```
