### ISSUE TITLE
Email alerts every time I start OpenCanary

### ISSUE THREAD

**Issue by Emi94** [thinkst/opencanary#49]
Hi,

I have enabled email alerts and every time I start OpenCanary it produces some logs that are sent as emails. These are the logs I'm talking about:

> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:18.914888", "logdata": {"msg": {"logdata": "Added service from class Telnet in opencanary.modules.telnet to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:19.081700", "logdata": {"msg": {"logdata": "Added service from class CanaryHTTP in opencanary.modules.http to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:19.212972", "logdata": {"msg": {"logdata": "Added service from class CanaryFTP in opencanary.modules.ftp to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:19.311152", "logdata": {"msg": {"logdata": "Added service from class CanarySSH in opencanary.modules.ssh to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:19.389432", "logdata": {"msg": {"logdata": "Added service from class CanaryMySQL in opencanary.modules.mysql to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:19.483347", "logdata": {"msg": {"logdata": "Added service from class CanaryTftp in opencanary.modules.tftp to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:19.523974", "logdata": {"msg": {"logdata": "Added service from class CanaryNtp in opencanary.modules.ntp to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:19.599323", "logdata": {"msg": {"logdata": "Added service from class CanarySIP in opencanary.modules.sip to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:20.232800", "logdata": {"msg": {"logdata": "Added service from class CanaryRDP in opencanary.modules.rdp to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:20.331103", "logdata": {"msg": {"logdata": "Added service from class CanarySNMP in opencanary.modules.snmp to fake"}}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}
> {"dst_host": "", "dst_port": -1, "local_time": "2018-08-01 10:44:20.421496", "logdata": {"msg": "Canary running!!!"}, "logtype": 1001, "node_id": "opencanary-1", "src_host": "", "src_port": -1}

Can this be suppressed directly from the software?

**Comment by thinkst** [comment]
Hey @Emi94,

Sorry for the delay. Would you mind giving me a little more information? How did you enable email alerts? Which email provider are you using? 

These logs should not be alerting you as they are simply telling you which services are starting. I will look into this more (while I wait for some more information form you.)

Thanks

**Comment by Emi94** [comment]
I used postfix to send emails and enabled opencanary to send them as described here: https://opencanary.readthedocs.io/en/latest/alerts/email.html#send-with-smtp-authentication

This is how it looks:
```
"SMTP": {
        "class": "logging.handlers.SMTPHandler",
        "mailhost": ["localhost", 25],
        "fromaddr": "alerts@mydomain.com",
        "toaddrs" : ["name@mydomain.com"],
        "subject" : "OpenCanary Alert"
}
```

As a guess I'd say that opencanary simply sends an alert for every written log.

**Comment by thinkst** [comment]
Hey @Emi94,

I have taken a look. I think the wording is misleading, but you setup up a loghandler (in OpenCanary). This means that anytime an OpenCanary service logs something, it will send that data through the various log handlers specified. 

If you are looking for something more robust in handling the OpenCanary incidents, I would suggest looking at the https://github.com/thinkst/opencanary-correlator . It may be easier to configure OpenCanary Correlator to handle new email credentials if need be rather then monkey patching OpenCanary to send certain logs to certain log handlers.

Please let me know if this sounds reasonable (otherwise we can try brainstorm some ways around this!).

**Comment by jayjb** [comment]
Closing this issue. Please reopen if you would like to continue the discussion.
