### ISSUE TITLE
Excluding (whitelisting) known IP's from alerts

### ISSUE THREAD

**Issue by bgarlock** [thinkst/opencanary#54]
We have a couple of monitoring servers (Spiceworks and Solarwinds) that scan subnets to check server status and port status of IP's.  Other than excluding the opencanary server in each monitoring server from scanning, is there a way to "whitelist" a couple of IP's from triggering alerts?

**Comment by thinkst** [comment]
Hey @bgarlock,

Sorry for the delay in my response. Currently the OpenCanary project doesn't support whitelisting IPs, but it could be added to the `log` method into the `__init__.py` inside the modules folder. 

You could add a config key,value pair like `ip.whitelist: [value1, value2]`. 

Then check if the attacker IP is in config, much like we check the port number for services in the modules folder.

Please let me know how this goes. (We always happy with PRs and reward handsomely with swag ;) )

**Comment by thinkst** [comment]
hey @p1r06u3,

That is very cool. We always encourage contributions and pull requests. 

Thanks for taking an interest and running with it.

**Comment by jayjb** [comment]
Closing this issue. Please reopen if you would like to continue this discussion.
