### ISSUE TITLE
DST Port 631 - Alert every 10 minutes

### ISSUE THREAD

**Issue by dsikic** [thinkst/opencanary#56]
How to make these stop? In the config, I don't see any service which is running on this port, yet I receive an email about this every 10 minutes or less. Everything is default, except almost all services are on.

**{"dst_host": "127.0.0.1", "dst_port": "631", "local_time": "2019-01-02 12:20:54.170414", "logdata": {"DF": "", "ID": "57201", "IN": "lo", "LEN": "60", "MAC": "00:00:00:00:00:00:00:00:00:00:00:00:08:00", "OUT": "", "PREC": "0x00", "PROTO": "TCP", "RES": "0x00", "SYN": "", "TOS": "0x00", "TTL": "64", "URGP": "0", "WINDOW": "43690"}, "logtype": 5001, "node_id": "opencanary-1", "src_host": "127.0.0.1", "src_port": "52442"}**

**Comment by thinkst** [comment]
Hey @dsikic,

The logtype that is exposed there tells us that it is a portscan incident. This means that someone/something is scanning your device for port 631 (which is a traditional CUPS server port). 

To stop the portscan incidents, you would need to set the config value `portscan.enabled` to `false`.

Please let me know if you need any more explanations or help.

**Comment by dsikic** [comment]
Hi @thinkst,

Thank you for the prompt response. If src_host is 127.0.0.1 wouldn't that rule out another machine on the network, or does that not apply for this logtype?

Thanks.
Denis

**Comment by thinkst** [comment]
Hey @dsikic,

That is interesting (sorry i didnt notice that at first). What OS and version are you running opencanary on? I can try replicate the issue and figure out whats going on. At this point, im wondering if it is something on the same machine that is checking for printer functionality (or something like that).

**Comment by dsikic** [comment]
@thinkst 

I'm using Raspberry Pi Zero wireless, running Raspbian with UI configured, all defaults except every option turned on in your config and an SMTP log forwarder set up. What do you need from me?

Thanks again!
Denis

**Comment by thinkst** [comment]
Hey @dsikic,

Thanks for the info. Ive tried to replicate your issue (without having a Raspberry Pi Zero wireless). What I did notice however, is that the `dst_host` and `src_host` are `127.0.0.1` in your incident, whereas if it was something externally portscanning your OpenCanary, we would see something like, 

`{"dst_host": "192.168.1.88", "dst_port": "23", "local_time": "2019-01-14 15:10:28.691498", "logdata": {"DF": "", "ID": "0", "IN": "enp0s3", "LEN": "64", "MAC": "08:00:27:97:7b:0c:3c:15:c2:ca:0a:ce:08:00", "OUT": "", "PREC": "0x00", "PROTO": "TCP", "RES": "0x00", "SYN": "", "TOS": "0x00", "TTL": "255", "URGP": "0", "WINDOW": "65535"}, "logtype": 5001, "node_id": "bob", "src_host": "192.168.1.22", "src_port": "58868"}`

where the `dst_host` and `src_host` are populated with the target IP and source IP respectively. 

I decided to also try run `nmap 127.0.0.1` from the machine running OpenCanary. I got very similar results to you,

`{"dst_host": "127.0.0.1", "dst_port": "631", "local_time": "2019-01-14 15:20:12.883580", "logdata": {"ACK": "", "DF": "", "ID": "36688", "IN": "lo", "LEN": "40", "MAC": "00:00:00:00:00:00:00:00:00:00:00:00:08:00", "OUT": "", "PREC": "0x00", "PROTO": "TCP", "RES": "0x00", "RST": "", "TOS": "0x00", "TTL": "64", "URGP": "0", "WINDOW": "0"}, "logtype": 5001, "node_id": "bob", "src_host": "127.0.0.1", "src_port": "587"}`

This leads me to think that there is some process running on your raspberry pi that is causing this issue. Ill try see if there is some process that comes standard with Raspbian that may be casuing this issue.

**Comment by ajhubs** [comment]
Hi 

Did anyone figure out what was causing this as I have the same problem on Ubuntu Server 18.04 ? 

Iv tried blocking localhost access to localhost on that port with UFW but this has not helped

Thanks

**Comment by thinkst** [comment]
Hey @ajhubs,

We didn't conclude on why it was happening unfortunately, but Ill try it with Ubuntu Server 18.04 and see if I can replicate and figure whats going on. And get back to you.

**Comment by ajhubs** [comment]
Thanks
It would be really good if I didn’t have to turn off port scan detection because this, as it’s so useful.
Happy to test anything you can think of and report back if needed.

**Comment by dsikic** [comment]
I’ve been living with dozens of emails a day, waiting to hear back on this ticket.

Sent from my iPad

On Apr 30, 2019, at 9:28 AM, ajhubs <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks
It would be really good if I didn’t have to turn off port scan detection because this, as it’s so useful.
Happy to test anything you can think of and report back if needed.

**Comment by thinkst** [comment]
Hey @dsikic, @ajhubs,

Im just setting up testing rigs of both raspbian and ubuntu. My initial tests don't replicate your issues (yet). The one thing I did notice from the logs generated by the portscan module is that on an actual portscan from another host, both IPs are present. So `dst_host` would be the targeted host ip i.e. the system running opencanary while the `src_host` be offending ip i.e. the system running the portscan. 

In your example logs both those addresses are populated by `127.0.0.1` which again points to something on the same system running opencanary. It may be some program/process that is checking for a CUPS server (if hitting port 631). Ill report back with more findings shortly.

**Comment by dsikic** [comment]
Any luck? I’m seriously considering turning this thing off now.

On May 2, 2019, at 09:33, Thinkst Applied Research <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @dsikic<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsikic&data=02%7C01%7C%7C48701c9580434045423f08d6cf02b87c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636924007919769300&sdata=xCA%2B32bFiVy5nLWUA00Sq0uhHjyKz2xbzknP%2FdGjx0U%3D&reserved=0>, @ajhubs<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fajhubs&data=02%7C01%7C%7C48701c9580434045423f08d6cf02b87c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636924007919779323&sdata=lgBL3%2FsyxA3SDqYLiiioAyqOnhrEhXLK%2FHyIZFH4MG4%3D&reserved=0>,

Im just setting up testing rigs of both raspbian and ubuntu. My initial tests don't replicate your issues (yet). The one thing I did notice from the logs generated by the portscan module is that on an actual portscan from another host, both IPs are present. So dst_host would be the targeted host ip i.e. the system running opencanary while the src_host be offending ip i.e. the system running the portscan.

In your example logs both those addresses are populated by 127.0.0.1 which again points to something on the same system running opencanary. It may be some program/process that is checking for a CUPS server (if hitting port 631). Ill report back with more findings shortly.

**Comment by byronsims** [comment]
I am having this issue as well.  Running latest version of raspbian lite. Nothing installed except what comes with the OS and 


{"dst_host": "127.0.0.1", "dst_port": "631", "local_time": "2019-07-24 09:16:03.859120", "logdata": {"DF": "", "ID": "539", "IN": "lo", "LEN": "60", "MAC": "00:00:00:00:00:00:00:00:00:00:00:00:08:00", "OUT": "", "PREC": "0x00", "PROTO": "TCP", "RES": "0x00", "SYN": "", "TOS": "0x00", "TTL": "64", "URGP": "0", "WINDOW": "43690"}, "logtype": 5001, "node_id": "myhostname", "src_host": "127.0.0.1", "src_port": "57762"}

**Comment by dsikic** [comment]
I just ended up unplugging mine.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ajhubs** [comment]
Ok I think I have resolved this issue on my canary !

As port 631 is supposed to be the CUPS printer port, (but not in use in my case) as Im running Ubuntu server 18.04 "lite" with no GUI and minimal default packages, it got me thinking I wonder if something on the OS is querying if it has a printer service running, and as it never get a response, it just keeps checking randomly, so I installed CUPS "sudo apt install cups" and the issue when away !!! :)

@dsikic  - from what I can see CUPS is not installed in raspian by default so you may have the same issue.

**Comment by dsikic** [comment]
Thank you @ajhubs
I’ll give it a shot and report back.

On Aug 5, 2019, at 19:29, ajhubs <notifications@github.com<mailto:notifications@github.com>> wrote:

CUPS

**Comment by jayjb** [comment]
Hi @ajhubs,

Thats a great find. The original hypothesis was that there was some process checking whether the printer service is running, but I did not think that if nothing responded it would continue trying. Thanks so much for reporting this fix. Would you mind emailing me `jay` [at] `thinkst.com` please?

**Comment by dsikic** [comment]
I can confirm that it works.

Sent from my iPad

On Sep 30, 2019, at 13:04, JayJB <notifications@github.com> wrote:

﻿

Hi @ajhubs<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fajhubs&data=02%7C01%7C%7C9c119c3b664c4525e38408d745c8515d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637054598961047806&sdata=nPoOXrk1B%2FYYtGU%2FcJM5pf15GAqaXq%2BF4WOfaV8p4eE%3D&reserved=0>,

Thats a great find. The original hypothesis was that there was some process checking whether the printer service is running, but I did not think that if nothing responded it would continue trying. Thanks so much for reporting this fix. Would you mind emailing me jay [at] thinkst.com please?

**Comment by LMNTRIXCORP** [comment]
@jayjb Also I have noticed that if you have printer block in samba conf and your samba accessed by outside then it will generate 631 port scan alert.

**Comment by prashantvidja** [comment]
@jayjb 
I have noticed that if we keep below block in smb.conf and access file using samba then we get 631 alerts.

> [printers]
>    comment = All Printers
>    browseable = no
>    path = /var/spool/samba
>    printable = yes
>    guest ok = no
>    read only = yes
>    create mask = 0700

The upper block is by default in smb.conf.
See if it can solve the issue.

Thanks

**Comment by jayjb** [comment]
hi @prashantvidja,

Ah thats interesting. Im making a list of things i need to test and report back with more info. Ill add this to the list. 

Thanks so much

**Comment by Tam-Lin** [comment]
samba is built with printing support by default.  I disabled printer sharing using 
https://wiki.samba.org/index.php/Setting_up_Samba_as_a_Print_Server#Disabling_the_Automatic_Printer_Sharing , and commenting out the printer shares in smb.conf, and at least so far, no more messages.

**Comment by bigfatfrog67** [comment]
> Ok I think I have resolved this issue on my canary !
> 
> As port 631 is supposed to be the CUPS printer port, (but not in use in my case) as Im running Ubuntu server 18.04 "lite" with no GUI and minimal default packages, it got me thinking I wonder if something on the OS is querying if it has a printer service running, and as it never get a response, it just keeps checking randomly, so I installed CUPS "sudo apt install cups" and the issue when away !!! :)
> 
> @dsikic - from what I can see CUPS is not installed in raspian by default so you may have the same issue.

I had the same issue using OpenCanary on a Pi Zero Wireless, periodic reports on port 631. I've installed CUPS and all seems quiet!

Thanks everyone for tracking this down.

**Comment by jc19knoxNV** [comment]
Thanks @Tam-Lin

@bigfatfrog67 installing CUPS was not the right thing to do.  Disabling the printer stuff in samba is the right thing to do.

The real solution for canary is actually to ignore 127.0.0.1, if there were a breach locally then canary is of no use anyway...

**Comment by jc19knoxNV** [comment]
This is all moot and 127.0.0.1 doesn't need to be reported on. If the host OS is compromised then OpenCanary is of no use anyway...

**Comment by jayjb** [comment]
Hi @jc19knoxNV,

Totally makes sense. I would like to rework logging vs notification channels. Which would mean only alerts through to channels like email or webhook while other channels like syslog or file would handle logging.

**Comment by jayjb** [comment]
Closing this thread because ive updated the FAQ with methods to avoid 631 alerts and added an `smb.ignore_localhost` paramter feature to list of action items.
