### ISSUE TITLE
Samba alert being sent multiple times.

### ISSUE THREAD

**Issue by citnadxela** [thinkst/opencanary#57]
I believe I got the Samba share working.  Whenever a file is accessed by myself or another person, I get an e-mail alert.  However, it will send multiple alerts of the same thing.  For example, this is what it says in all the e-mails following the initial alert e-mail:
![image](https://user-images.githubusercontent.com/40772046/51054338-6de9f080-1591-11e9-8599-6d17d1bd274d.png)

Is there any way to resolve this or do I have something configured incorrectly?

**Comment by thinkst** [comment]
Hey @citnadxela,

So the explanation here is that we are alerting based on whats coming through in the logs. In the logs you will see that it reports each read (which for some files may take more then one read operation). This means we would see multiple alerts for the same file being opened. 

We haven't added support to handle this nicely (yet!). You could add it by looking at the `samba.py` file, and adding some logic to determine whether it is the same file (under `SambaLogWatcher` and in `handleLines`). This PR would be welcomed (and rewarded) 😋
