### ISSUE TITLE
What is the opensource License of the opencanary?

### ISSUE THREAD

**Issue by p1r06u3** [thinkst/opencanary#58]
What is the opensource License of the opencanary?

**Comment by thinkst** [comment]
Hey @p1r06u3,

Opencanary is licensed under BSD 3-Clause "New" or "Revised" License. You can read more about that in the [LICENSE](https://github.com/thinkst/opencanary/blob/master/LICENSE).

Please let me know if you have any other questions. I really think your opencanary web stuff is great.

**Comment by p1r06u3** [comment]
Thank you for your recognition.
Because in the issue https://github.com/p1r06u3/opencanary_web/issues/19 that asked me the opencanary_web's License. I think it belong to Thinkst opencanary honeypot, so I know how to reply her question.

**Comment by thinkst** [comment]
Closing this as resolved 🤘
