### ISSUE TITLE
opencanaryd --start not working

### ISSUE THREAD

**Issue by rustempasha** [thinkst/opencanary#6]
Hi. I've installed opencanary on virtualenv following instructions on both Debian x86 / 64. I've done the configuration on json file however when I type opencanaryd --start, the shell says /usr/local/bin/opencanaryd: line 23: sudo: command not found. I opened the opencanaryd file and see that there is no opencanaryd.pid file maybe the problem is that. Thanks.

**Comment by thinkst** [comment]
Hi,

It looks like the opencanaryd is complaining about not having 'sudo' installed. Could you try installing that first?

The opencanaryd script should, but doesn't yet, check for the existence of sudo before using it as most of our testing takes place on Ubuntu.

**Comment by rustempasha** [comment]
yes sudo is not installed my system i've solved the issue thank you.
