### ISSUE TITLE
VNC not generate any alert for Mac os.

### ISSUE THREAD

**Issue by prashantvidja** [thinkst/opencanary#60]
Hello,

I have installed open-canary in my vmware and enabled VNC service in conf file on 5000 port.

if I connect from other Ubuntu machine from same network then it is generating alert.

But from Mac Os sierra10.12 it is not working using default VNC client **screen sharing**,  but when I used **realvnc** third party client in mac then it also generate alert.

why mac default VNC client not generating alert?

Thanks & Regards

**Comment by thinkst** [comment]
Hey @prashantvidja,

Thanks for bringing our attention to this. Ill investigate it and get back to you.

**Comment by thinkst** [comment]
hey @prashantvidja,

Thanks again for bringing this up. The short answer is that our VNC implementation only supports one of the three (the latest and most common) RFB protocol versions. 

If you would like to extend the `vnc.py` module, we would gladly accept a PR (and send some swag for helping out!).

**Comment by prashantvidja** [comment]
Thanks,
Resolved in new release 0.5.1.
