### ISSUE TITLE
samba-audit.log file not watched

### ISSUE THREAD

**Issue by greg-dobedobedo** [thinkst/opencanary#61]
I used to have the samba events handled by opencanary logger but it does not seem to be the case anymore. 

twistd has a file descriptor for this file, so the configuration seems ok:

root@a8de6856982e:/# lsof /var/log/samba-audit.log
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
twistd     1 root   11r   REG    8,1      392 1971342 /var/log/samba-audit.log
rsyslogd  46 root    6w   REG    8,1      392 1971342 /var/log/samba-audit.log

After opening a file on the share, the samba-audit.log size is 1312B:

root@a8de6856982e:/# ls -al /var/log/samba-audit.log
-rw-r--r-- 1 root adm 1312 Feb 27 10:35 /var/log/samba-audit.log

root@a8de6856982e:/# cat /var/log/samba-audit.log
Feb 27 10:33:24 a8de6856982e liblogging-stdlog:  [origin software="rsyslogd" swVersion="8.24.0" x-pid="46" x-info="http://www.rsyslog.com"] start
Feb 27 10:33:25 a8de6856982e liblogging-stdlog: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
Feb 27 10:33:25 a8de6856982e liblogging-stdlog: activation of module imklog failed [v8.24.0 try http://www.rsyslog.com/e/2145 ]
Feb 27 10:35:07 a8de6856982e smbd_audit: john|10.91.1.242|172.18.0.3|wks222|accounting|acc-server|SMB3_11|OSX|2019/02/27 10:35:07|ACC-SERVER|pread|ok|2015-ACC-Salaries-NB92.docx
(...)

But the twistd file descriptor position is still 146 (end of the first line):
root@a8de6856982e:/# cat /proc/1/fdinfo/11
pos:    146
flags:  0100000
mnt_id: 208

It seems that the FileSystemWatcher object is stuck at the first line and I have no clues why.

opencanary is running in a docker container from a debian 9.8 with Python 2.7.15

**Comment by thinkst** [comment]
Hey @greg-dobedobedo,

Thanks for all the info. Im trying to get setup so that I can try reproduce the issue. Would you mind providing me with what your `smb.conf` looks like?

**Comment by greg-dobedobedo** [comment]
Hi @thinkst 

Sure:
```
[global]
       workgroup = ACCOUNTING
       server string = Windows 2003 File Server
       netbios name = ACC-SERVER
       dns proxy = no
       log file = /var/log/samba/log.all
       log level = 0
       vfs object = full_audit
       full_audit:prefix = %U|%I|%i|%m|%S|%L|%R|%a|%T|%D
       full_audit:success = pread
       full_audit:failure = none
       full_audit:facility = local7
       full_audit:priority = notice
       max log size = 100
       panic action = /usr/share/samba/panic-action %d

       #samba 4
       server role = standalone server

       #samba 3
       #security = user

       passdb backend = tdbsam
       obey pam restrictions = yes
       unix password sync = no
       map to guest = bad user
       usershare allow guests = yes

[accounting]
       comment = Accounting Documents
       path = /storage/smb
       guest ok = yes
       read only = yes
       browseable = yes
```

**Comment by thinkst** [comment]
Hey @greg-dobedobedo,

Thanks for the additional info. I have tried to replicate your issue without any success. Does restarting the opencanary process rectify this issue? 

We have started working on a new way in which to monitor these Samba events since the log file watcher can be unstable at times.

**Comment by greg-dobedobedo** [comment]
Hi @thinkst, I forgot to mention I also have an additional syslog handler. Here is the opencanary.conf file:

```
{
    "device.node_id": "smbnode1",
    "logger": {
        "class": "PyLogger",
        "kwargs": {
            "formatters": {
                "plain": {
                    "format": "%(message)s"
                }
            },
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                    "stream": "ext://sys.stdout"
                },
                "file": {
                    "class": "logging.FileHandler",
                    "filename": "/var/log/opencanary.log"
                },
                "syslog-unix": {
                    "class": "logging.handlers.SysLogHandler",
                    "address": [
                        "splunkfwd.dts.corp.local",
                        1527
                    ],
                    "socktype": "ext://socket.SOCK_DGRAM"
                }
            }
        }
    },
    "portscan.synrate": 5,
    "smb.auditfile": "/var/log/samba-audit.log",
    "smb.enabled": true
}
```

If this new handler cannot change the way the FileSystemWatcher work (and I don't see why), I guess the issue is related to the fact I'm using a docker image, based on python:2.7-slim-stretch, with a different behavior of sysVinit (for instance no init process). My CMD instruction is a script which mainly launch:

```
        service samba start
        service rsyslog start
        exec "/usr/local/bin/twistd" -noy "/usr/local/bin/opencanary.tac" --pidfile "/opencanaryd.pid"
```

**Comment by thinkst** [comment]
Hey @greg-dobedobedo,

Thanks for the update. Thats an interesting (and cool) setup you trying to get going. 

In terms of the exec command, maybe try using the exact one that we use in the `opencanaryd` script which is 
`"/usr/local/bin/twistd" -y "/usr/local/bin/opencanary.tac" --pidfile "/opencanaryd.pid" --syslog --prefix=opencanaryd`.

Im going to try build up an OpenCanary docker with your specs too and see if I have any luck.

**Comment by greg-dobedobedo** [comment]
@thinkst, if you are comfortable with Docker, here is my simplified Dockerfile.

I would like to share the whole sources, but it requires some documentation. My image contains several canary profiles (actually opencanary.conf files). The profile to use is defined by an environment variable CANARY_TYPE defined in the compose file.

```
FROM python:2.7-slim-stretch

# Requirements
RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y \
	python-pip \
	samba \
	python-libpcap \
	libpcap0.8 \
	libpcap0.8-dev \
	rsyslog \
    build-essential \
    libssl-dev \
	libffi-dev \
	python-dev \
	sudo \
	&& rm -rf /var/lib/apt/lists/*

# Install opencanary 
RUN pip install --upgrade pip ; pip install opencanary scapy pcapy pylogger

# Configure samba
COPY ./src/conf/samba/smb.conf /etc/samba/
# Configure rsyslog for samba logs
COPY ./src/conf/rsyslog/rsyslog.conf /etc/
# Configure opencanary
COPY ./src/conf/opencanaryd /etc/opencanaryd/
# Configure SMB storage
COPY ./src/storage/smb/ /storage/smb/
RUN chmod -R o+r /storage/smb/

# CMD configuration
COPY ./src/start.sh /
RUN chmod +x /start.sh
CMD ["/start.sh"]
```

**Comment by thinkst** [comment]
Hey @greg-dobedobedo,

Thats really cool. Thanks for the Dockerfile (im trying a slightly different way of doing it). 

Can I ask that if you nmap the docker container, does it show the exposed ports of the services that you have enabled?

**Comment by greg-dobedobedo** [comment]
@thinkst, yes it show the exposed ports. Better than that, I can browse the share, open the fake document and events are created in the samba-audit.log.
For other profiles such as SSH or FTP, service and logs work fine.

**Comment by prashantvidja** [comment]
@greg-dobedobedo @thinkst 

Does portscan module is working for that?

Thanks

**Comment by thinkst** [comment]
hey @greg-dobedobedo,

Sorry for the delay in my response. Did you come right with the smb?

**Comment by greg-dobedobedo** [comment]
Hello @thinkst, 

Unfortunately, I didn't have time to progress on it. I know that twistd has a file descriptor on the /var/log/samba-audit.log but does not follow it when new lines come.
I have no clue why it would be related to docker.

@prashantvidja, I haven't tested it actually. I don't know how this will react in a docker container, even in the "host" network mode. I should expose multiples ports. But this is a nice test to do.

**Comment by prashantvidja** [comment]
@thinkst Thanks for your replay.
Yes you are right, I have already tested that using "host" network mode. And it is works for me.
And also we must need to start rsyslog in container otherwise it will not generate alert for portscan.

**Comment by greg-dobedobedo** [comment]
I have exactly the same behavior on a standard centos 7.6, with the same configuration.

And I finally found the cause. This is the presence of the parameter 'portscan.synrate' in my opencanary.conf:

```
    "portscan.synrate": 5,
    "smb.auditfile": "/var/log/samba-audit.log",
    "smb.enabled": true
```

I didn't configure anything on IPTables to make the portscan works. I guess the watch of an unexisting /var/log/kern.log makes the file watch process stuck.

@prashantvidja was right when asking about the portscan module.

Problem solved \o/
