### ISSUE TITLE
error with running SSH

### ISSUE THREAD

**Issue by 2raziel3** [thinkst/opencanary#64]
Hi,

I have got http, telent and FTP working and logging locally, however when I enable SSH i am getting an error when starting ;

{"dst_host": "", "dst_port": -1, "local_time": "2019-03-19 15:37:57.272196", "logdata": 
{"msg": 
{"logdata": "Failed to add service from class CanarySSH in opencanary.modules.ssh. 
Traceback (most recent call last):\n

File \"/home/ubuntu/env/bin/opencanary.tac\", line 88, in start_mod\n    service = obj.getService()\n 

File \"/home/ubuntu/env/local/lib/python2.7/site-packages/opencanary/modules/ssh.py\", line 374, in getService\n    rsa_pubKeyString, rsa_privKeyString = getRSAKeys()\n  

File \"/home/ubuntu/env/local/lib/python2.7/site-packages/opencanary/modules/ssh.py\", line 300, in getRSAKeys\n    publicKeyString = keys.Key(rsaKey).public().toString('openssh')\n  

File \"/home/ubuntu/env/local/lib/python2.7/site-packages/twisted/conch/ssh/keys.py\", line 794, in public\n    return Key(self._keyObject.public_key())\n  

File \"/home/ubuntu/env/local/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py\", line 126, in __getattr__\n    raise AttributeError(\"%s object has no %r attribute\" % (self.__class__.__name__, attrname,))\nAttributeError: _RSAobj object has no 'public_key' attribute\n"}}, "logtype": 1001, "node_id": "foobar.com", "src_host": "", "src_port": -1}

**Comment by 2raziel3** [comment]
I am running the following ssh;
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, openSSL 1.0.2g 1 Mar 2016

I have tried changing the config to;
"ssh.version": "SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8",
"ssh.version": "OpenSSH_7.2p2 Ubuntu-4ubuntu2.8",

I also tried generating new keys, all of these are resulting in the same error.

**Comment by 2raziel3** [comment]
Hi,

looking through your ssh.py module i saw that your SSH_PATH="/var/tmp"
looking through this i found that there were no SSH keys in that directory.
By copying the ssh keys i generated in the default ~\.ssh  directory i resolved the above issue but was presented with a new one;

{"dst_host": "", "dst_port": -1, "local_time": "2019-03-22 09:51:13.272196", "logdata":
{"msg":
{"logdata": "Failed to add service from class CanarySSH in opencanary.modules.ssh.
Traceback (most recent call last):\n

File "/root/env/local/lib/python2.7/site-packages/opencanary/modules/ssh.py", line 375, in getService\n dsa_pubKeyString, dsa_privKeyString = getDSAKeys()\n

File "/root/env/local/lib/python2.7/site-packages/opencanary/modules/ssh.py", line 322, in getDSAKeys\n publicKeyString = keys.Key(dsaKey).public().toString('openssh')\n

File "/root/env/local/lib/python2.7/site-packages/twisted/conch/ssh/keys.py", line 794, in public\n return Key(self._keyObject.public_key())\n

File "root/env/local/lib/python2.7/site-packages/Crypto/PublicKey/DSA.py", line 125, in getattr\n raise AttributeError("%s object has no %r attribute" % (self.class.name, attrname,))\nAttributeError: _DSAobj object has no 'public_key' attribute\n"}}, "logtype": 1001, "node_id": "foobar.com", "src_host": "", "src_port": -1}

**Comment by 2raziel3** [comment]
resolved this issue by generating keys using DSA and transferring them to /var/tmp
a note for anyone else who has this issue I had to generate the keys without passphrases.
@thinkst if there is a way to pass these passphrases in the config could you let me know :)

**Comment by thinkst** [comment]
Hey @2raziel3,

Sorry for the delay in my response. Well done on getting that first issue sorted. For the current one, you will have to repeat those steps and generate `DSA` keys in the same path, labelled `id_dsa.pub` and `id_dsa` as it seems the method that should be generating them for you is failing. 

I would love to know if you tried to run 
`
from Crypto.PublicKey import DSA
from twisted.python import randbytes
KEY_LENGTH = 1024
dsaKey = DSA.generate(KEY_LENGTH, randbytes.secureRandom)
publicKeyString = keys.Key(dsaKey).public().toString('openssh')
privateKeyString = keys.Key(dsaKey).toString('openssh')
`
if it completes successfully. We have seen this issue you reporting very rarely and im trying to get a sense of when we can expect this key generation process to fail. 

Please let me know how it goes and we can continue debugging this.

**Comment by thinkst** [comment]
@2raziel3 I glad you got it sorted and thanks for noting it for us for future problems. 

Out of interest, what OS are you trying to run your OpenCanary on? We have seen this issue crop up here and there, but nothing definitive in terms of why. I suspect that `.generate` step is failing silently and so the next method fails because the keys weren't generated correctly.

**Comment by 2raziel3** [comment]
Hi,

no worries on the delay, the fact you support this open source solution at all is pretty awesome :) .
I have tried running the key generation above but I am getting an error on line 5, where its stating 
'keys' is not defined.

understandably i am getting the same error in line 6.

ran the code twice to check if i had made an error, seems not to be the case.

**Comment by 2raziel3** [comment]
I am running on ubuntu 18.04 .
however i had the same issue on 16.04 and ubuntu mate and rasbian.

**Comment by thinkst** [comment]
Ah well spotted.  You would need to import
`from twisted.conch.ssh import keys`

**Comment by 2raziel3** [comment]
so following that import I am getting the error I had before where the _DSAobj has no 'public_key' attribute. So looks like as you said the automated key generation is not happening.

**Comment by thinkst** [comment]
Thanks for following up. Ill take a look into why this happens. Thanks @2raziel3

**Comment by 2raziel3** [comment]
@thinkst your welcome

**Comment by prashantvidja** [comment]
It is working in twisted 14.0.2. not in 18.4.0.
So downgrade this version and it will work fine.

**Comment by thinkst** [comment]
@2raziel3 please let me know if downgrading the twisted version fixes this?

**Comment by prashantvidja** [comment]
@thinkst yes.

**Comment by 2raziel3** [comment]
@thinkst sorry but I am on holiday for the next few weeks, I can pick this up when i get back.

**Comment by thinkst** [comment]
@prashantvidja I am currently running the latest version with ssh working (and alerting). I don't suspect it is a python issue. I suspect the issue is connected to not being able to generate DSA and RSA keys. 

@2raziel3 thanks, that would be great. Enjoy your holiday!

**Comment by p-doyle** [comment]
I was having the same issue as 2raziel3 on Ubuntu 18.04.2.  Confirming downgrading twisted to 14.0.2 solved the issue.

**Comment by 2raziel3** [comment]
Hi,

Sorry I have not tested the downgrade myself yet, have a deadline on
another project. Although based on two people having the dame results I
would think it's defiantly changes made to twisted.

**Comment by thinkst** [comment]
Hey @2raziel3, @p-doyle, @prashantvidja,

Thank you so much for debugging and sending through info. Would you mind repulling your opencanary version? Ive bumped the version to 0.5.2 (which should fix this SSH issue).

The issue, for those wondering, was that the new Twisted version was referencing a different variable in its keys library for the public. I have changed the crypto library we use to be a library that is still active and being developed. 

Please ping me if you find any other issues or have any other queries.

**Comment by p-doyle** [comment]
After updating it seems to work.  Thanks for such a quick turnaround on this!

**Comment by 2raziel3** [comment]
Hi @thinkst , 

Sorry for the delay, just re-built from master and the SSH keys are auto-generating.
Happy that this is resolved, and thanks for taking the time to do it.
