### ISSUE TITLE
Can not input password for rdp honeypot

### ISSUE THREAD

**Issue by p1r06u3** [thinkst/opencanary#70]
Hi, I try to connect rdp honeypot server with windows 2008 R2 destop and win10，but log 
 in processing I can not input password.
Because it isn't pop a Credentials window and then turn to self.doEvent(0) for rss. In mac os it will pop a Credentials window. Is it a pyrdp lib bug?

**Comment by jayjb** [comment]
Hey @p1r06u3,

Thanks for reporting this. Ill take a look and get back to you.

**Comment by jayjb** [comment]
We are looking at re-doing rdp since we haven't touched that code path in a while. Consider it broken at the moment.
