### ISSUE TITLE
Any plans to port to python3?

### ISSUE THREAD

**Issue by c-goosen** [thinkst/opencanary#71]
Hi.

Been interesting going through this project and attempting a py2 + py3 port.

Ive gotten fairly far, but seems at some point will hit breaking changes.

Any internal roadmap for py3?

Thanks

**Comment by c-goosen** [comment]
https://github.com/c-goosen/opencanary/commit/6b46ca0869b711df602be57f98f69096b4191b80#diff-f33d9ee52a40c9193ac84636f3529bdc
https://github.com/c-goosen/opencanary/commit/2ea3c399bac0f7b48f9d47699be5b2dab35b1c42

Gonna take a while to patch and test comparability on both py2&py3.

Trying to not break py2 completely

**Comment by HybridAU** [comment]
I've also been working on Python 3 support, also without breaking python 2. 

I created issue #33 and made a [pull request](https://github.com/thinkst/opencanary/pull/59). So far I've got the core of OpenCanary running under Python 3 a few of the core modules like FTP, Git, HTTP and SSH working.

I've also written a few basic tests to ensure that my changes don't break backwards compatibility.

**Comment by c-goosen** [comment]
Great will have a look.

Any issues you still have that can do with assistance?

**Comment by HybridAU** [comment]
That would be awesome, I've been planning on going through each of the modules in alphabetical order (just because that's the order they are displayed) and porting them to Python 3. I got FTP, Git and HTTP going but I'm currently stuck on httpproxy and I've got pretty limited free time so it's slow going.

If you could take a look, or even just write some more tests that would be really cool.

**Comment by c-goosen** [comment]
Will fork your repo and see If I can combine what ive done.

**Comment by jayjb** [comment]
Hey @HybridAU and @c-goosen,

Thanks so much for the consideration. We are planning to port (starting with @HybridAU's pull request). I am sorry it has taken so long, but ill try get to it this week. Thanks for the bump.

**Comment by c-goosen** [comment]
I will have a look as well see if there is anything not covered yet.

**Comment by c-goosen** [comment]
https://github.com/thinkst/opencanary/pull/72

**Comment by etiennemunnich** [comment]
(bump) any progress?

**Comment by jayjb** [comment]
hi @etiennemunnich,

I am slowly getting through it. I have a separate branch that is the python 3 port.

**Comment by jayjb** [comment]
DONE! yay!
