### ISSUE TITLE
customise module, link directory & function, but can't open port

### ISSUE THREAD

**Issue by Yokeen** [thinkst/opencanary#75]
My goal is to capture network traffic in real environments, such as tomcat. I set up a Tomcat folder. You visit it normally, and I get the traffic transferred.
i rewrite a tomcat module, that's my code  (modules/tomcat.py)
```
from opencanary.modules import CanaryService

from twisted.application import internet
from twisted.web.server import Site, GzipEncoderFactory
from twisted.web.resource import Resource, NoResource, EncodingResourceWrapper, ForbiddenResource
from twisted.web.util import Redirect
from twisted.web import static, twcgi

# -------------
from twisted.internet import reactor

import os
import re

class Tomcat(Resource):
    isLeaf = True

    def __init__(self, factory):
        self.factory = factory
    def render(self, request):
        request.setHeader('Server', 'apache testinfo')
        return Resource.render(self, request)
    def render_GET(self, request, loginFailed=False):
        us = request.transport.getHost()
        peer = request.transport.getPeer()
        logdata = {
            'HOSTNAME': request.getRequestHostname(),
        }

        logtype = self.factory.logger.LOG_HTTP_GET
        self.factory.log(logdata, transport=request.transport, logtype=logtype)
    
    def render_POST(self, request):
        return Resource.render_POST(self,request)

class CanaryTomcat(CanaryService):
    NAME = 'tomcat'

    def __init__(self, config=None, logger=None):
        CanaryService.__init__(self, config=config, logger=logger)
        self.skin = config.getVal('tomcat.skin', default='basicLogin')
        self.skindir = os.path.join(
            CanaryTomcat.resource_dir(), "skin", self.skin)
        # opencanary/modules/data/tomcat/skin/tomcatskin
        self.staticdir = os.path.join(self.skindir, "static")
        self.port = int(config.getVal('tomcat.port', default=80))
        ubanner = config.getVal('tomcat.banner', default="Apache/2.2.22 (Ubuntu)")
        self.banner = ubanner.encode('utf8')
        # StaticNoDirListing.BANNER = self.banner
        self.listen_addr = config.getVal('device.listen_addr', default='')

        self.tomcatdir = self.skindir + '/tomcat'

    def getService(self):
        root = Tomcat(factory=self)
        root.putChild("tmp",static.File("/tmp"))
        site = Site(root)
        return internet.TCPServer(self.port, site, interface=self.listen_addr)

```
im very very wonder, why when i empty class Tomcat 's __init__ function, my service can be run,Otherwise it won't.

Above code is the inability to run the service. when i empty __init__ function like this
```
from opencanary.modules import CanaryService

from twisted.application import internet
from twisted.web.server import Site, GzipEncoderFactory
from twisted.web.resource import Resource, NoResource, EncodingResourceWrapper, ForbiddenResource
from twisted.web.util import Redirect
from twisted.web import static, twcgi

# -------------
from twisted.internet import reactor

import os
import re

class Tomcat(Resource):
    isLeaf = True


    def render(self, request):
        request.setHeader('Server', 'apache testinfo')
        return Resource.render(self, request)
    def render_GET(self, request, loginFailed=False):
        us = request.transport.getHost()
        peer = request.transport.getPeer()
        logdata = {
            'HOSTNAME': request.getRequestHostname(),
        }

        logtype = self.factory.logger.LOG_HTTP_GET
        self.factory.log(logdata, transport=request.transport, logtype=logtype)
    
    def render_POST(self, request):
        return Resource.render_POST(self,request)

class CanaryTomcat(CanaryService):
    NAME = 'tomcat'

    def __init__(self, config=None, logger=None):
        CanaryService.__init__(self, config=config, logger=logger)
        self.skin = config.getVal('tomcat.skin', default='basicLogin')
        self.skindir = os.path.join(
            CanaryTomcat.resource_dir(), "skin", self.skin)
        # opencanary/modules/data/tomcat/skin/tomcatskin
        self.staticdir = os.path.join(self.skindir, "static")
        self.port = int(config.getVal('tomcat.port', default=80))
        ubanner = config.getVal('tomcat.banner', default="Apache/2.2.22 (Ubuntu)")
        self.banner = ubanner.encode('utf8')
        # StaticNoDirListing.BANNER = self.banner
        self.listen_addr = config.getVal('device.listen_addr', default='')

        self.tomcatdir = self.skindir + '/tomcat'

    def getService(self):
        root = Tomcat()
        root.putChild("tmp",static.File("/tmp"))
        site = Site(root)
        return internet.TCPServer(self.port, site, interface=self.listen_addr)

```

<img width="664" alt="1" src="https://user-images.githubusercontent.com/19142871/64154284-16233100-ce63-11e9-8040-50fca7a4649b.png">
<img width="678" alt="2" src="https://user-images.githubusercontent.com/19142871/64154331-3521c300-ce63-11e9-8550-a3df3eb857fb.png">
<img width="221" alt="3" src="https://user-images.githubusercontent.com/19142871/64154361-466acf80-ce63-11e9-89ac-b86296b4605e.png">

no factory,i can't obtain data packet........... hard。。

**Comment by Yokeen** [comment]
i already solve this problem, now i face other problem, how function getChild's parameter [name] can obtain directory???

**Comment by jayjb** [comment]
Hey @Yokeen,

Firstly this is very cool and im glad you making custom services. 

I dont think i understand your second question though. Can you send me a picture or more of an explanation so I can try help out please?

**Comment by Yokeen** [comment]
Hi @jayjb 

thank u reply me.
my second question is 【How getChild‘s attribute name Gets the path of Folders? such 127.0.0.1/manager/1.html】 i want to obtain /manager/1.html by attribute [name].

```
getChild(path, request) 
    .....
```
The resources requested in the URL can be obtain，

i see offical method：if  url like this **/foo/bar/baz**   you can use :

`site.resource.getChild('foo').getChild('bar').getChild('baz').`

In here: https://twistedmatrix.com/documents/current/api/twisted.web.resource.Resource.getChild.html

but i overwrite function getChild，I want to open different files according to the path of the URL，like this

<img width="395" alt="1" src="https://user-images.githubusercontent.com/19142871/64331405-53272900-d005-11e9-9982-de10dc5835c7.png">

but when i input url like 127.0.0.1/manager/index.html, the page return erro...
-------------------

last i  solve my second question, and this module can be run,

but i think my method is long and not conveniently

when i wang use directory's resource, i first register directory'name by putChild,  the other class can solve like 127.0.0.1/directory_name/xxxx  , like this
<img width="310" alt="2" src="https://user-images.githubusercontent.com/19142871/64331732-eceed600-d005-11e9-9225-f67e6fad2094.png">
<img width="210" alt="3" src="https://user-images.githubusercontent.com/19142871/64331882-2f181780-d006-11e9-9e9b-ed1c88a050d6.png">

it's very stupid. and I'm also trying to improve it.

**Comment by Yokeen** [comment]
name equal path
