### ISSUE TITLE
samba not works on ubuntu 19.10

### ISSUE THREAD

**Issue by prashantvidja** [thinkst/opencanary#79]
Hello,

I have installed an open-canary on ubuntu 19.10 within raspberry pi.
Samba not generating Syslog at /var/log/samba-audit.log.
Below is my samba conf.

>     [global]
>        workgroup = WORKGROUP
>        server string = blah
>        netbios name = SRV01
>        dns proxy = no
>        log file = /var/log/samba/log.all
>        log level = 0
>        vfs object = full_audit
>        full_audit:prefix = %U|%I|%i|%m|%S|%L|%R|%a|%T|%D
>        full_audit:success = pread
>        full_audit:failure = none
>        full_audit:facility = local7
>        full_audit:priority = notice
>        max log size = 100
>        panic action = /usr/share/samba/panic-action %d
> 
>        #samba 4
>        server role = standalone server
> 
>        #samba 3
>        #security = user
> 
>        passdb backend = tdbsam
>        obey pam restrictions = yes
>        unix password sync = no
>        map to guest = bad user
>        usershare allow guests = yes
>     [myshare]
>        comment = All the stuff!
>        path = /share
>        guest ok = yes
>        read only = yes
>        browseable = yes
>        #vfs object = audit

Also, I have done rsyslog.conf setting as well.
Did anyone fix this?

Thanks

**Comment by jayjb** [comment]
Hi @prashantvidja,

Thanks for reporting this. Ill take some time and try figure whats going wrong. I suspect that there are some Samba issues cropping up due to newer versions of Samba. It may be that Samba is logging somewhere different now. 

It may be worth checking this in steps. Checking that rsyslog is enabled. Checking that it redirects any `local7.*` to your destination you specified. Checking that Samba is logging at all (since we have setup the redirect, we monitor that, but actually it should be logging a bunch somewhere else too)

**Comment by prashantvidja** [comment]
Yeah, you are right, It's due to samba newer version.
And also I had verified that rsyslog is enabled. Also, it is not generating any logs using local7.*.

**Comment by nodauf** [comment]
@prashantvidja  it may be a little late be could you try with these events;
`connect disconnect opendir mkdir rmdir closedir open close read pread write pwrite sendfile rename unlink chmod fchmod chown fchown chdir ftruncate lock symlink readlink link mknod realpath` instead of `pread`

**Comment by jayjb** [comment]
@prashantvidja we've update the parsing of the samba logs. Let me know if it works for you in the new Opencanary version

**Comment by KMoonraiser** [comment]
I have the same issue. Samba is not generating the /var/log/samba-audit.log file. I can't tell if it's a Samba issue or a rsyslog problem.

BTW, the readme has a small error:

> Configure syslog to write the Samba logs out to the file that OpenCanary monitors. With rsyslog, adding these two lines to /etc/rsyslog will do that

should be

> Configure syslog to write the Samba logs out to the file that OpenCanary monitors. With rsyslog, adding these two lines to /etc/rsyslog.conf will do that

The Windows configuration page doesn't have this problem.

**Comment by jayjb** [comment]
Hi @KMoonraiser,

Thank you so much. You totally right. I've updated the wiki to reflrect with audit events to use that work (using 20.04).
