### ISSUE TITLE
Can this be run on any CPU architecture?

### ISSUE THREAD

**Issue by bcornw2** [thinkst/opencanary#80]
The only clues I've found in your documentation as to arch limitations seems to be in the MacOS install commands. 

My question: Can this be run on a RaspberryPi with ARM CPU architecture? Or is x64 required? What about x86?

Thanks,

Ben

**Comment by rotx** [comment]
I've had it running on a Raspberry 3 (Stretch, 32-bit armv7l) for the longest time, and have since migrated it to a Debian Buster VM on x86_64. The core is Python and will run almost anywhere. There is a dependency on Samba, but that's available everywhere as well.

**Comment by jayjb** [comment]
Hi @bcornw2,

@rotx is correct. For the basic operation of OpenCanary, you will need python2.7 (support for python3 is coming). There are some functions that may be system dependent though such as Samba. 

Please let me know if you have anymore questions.

**Comment by bcornw2** [comment]
Hi @rotx ,

I am trying to use this in pair with the OpenCanary Correlator (https://github.com/thinkst/opencanary-correlator/projects)

But I see that almost all of it has been out of development for more than 4 years. Is this module going to be updated to Python3 soon as well?

Thanks,

Ben

**Comment by jayjb** [comment]
Hi @bcornw2,

Currently we dont have any development plans for OpenCanary Correlator (https://github.com/thinkst/opencanary-correlator/projects). But this is mostly due to it working as expected. 

We could definitely revisit the project to get it python3 compatible if it is something that you are interested in.
