### ISSUE TITLE
Issue with SMTPhandler - cannot resolve

### ISSUE THREAD

**Issue by robertcdonovan** [thinkst/opencanary#81]
Having an issue with this error trying to get my first opencanary sensor to email directly to me instead of using a collector and dealing with mandrill (I assume still have to do that?). Installed on ubuntu 18.04 server.

> "handlers": {
                "SMTP": {
                        "class": "logging.handlers.SMTPhandler",
                        "mailhost": ["smtp.gmail.com", 587],
                        "fromaddr": "xxxxxxxxxx@gmail.com",
                        "toaddrs" : ["xxxxxxx@xxxxxxxxx.com"],
                        "subject" : "OpenCanary IMM1 Alert",
                        "credentials": ["xxxxxxxxxxxx@gmail.com", "xxxxxxxxxxxxxxxxxx                        "secure": []
                        },

This is the error I get 

> ** We hope you enjoy using OpenCanary. For more open source Canary goodness, head over to canarytokens.org. **
[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Using config file: /home/rcdonovan/.opencanary.conf
Invalid logging config
<type 'exceptions.ValueError'>
Unable to configure handler 'SMTP': Cannot resolve 'logging.handlers.SMTPhandler': No module named SMTPhandler

Stuck here.

**Comment by HybridAU** [comment]
I think it's a lowercase 'h' that's tripping you up. 

From the [python docs](https://docs.python.org/2/library/logging.handlers.html#smtphandler) it looks like it should be SMTPHandler

```Python
"handlers": {
"SMTP": {
"class": "logging.handlers.SMTPHandler",
"mailhost": ["smtp.gmail.com", 587],
# ...
```

Good luck and hopefully that helps :slightly_smiling_face:

**Comment by robertcdonovan** [comment]
Ha. Of course something similar. I'll give it a shot. Thank you.

**Comment by robertcdonovan** [comment]
That was it. Thanks again.
