### ISSUE TITLE
Can this be run on IPV6 network?

### ISSUE THREAD

**Issue by Vincebye** [thinkst/opencanary#82]
I need some help about how to deploy this honeypot on Ipv6 network.
I try to change the default in internet.TCPServer(self.port, f, interface=self.listen_addr)  to ::
but it not worked.

**Comment by HybridAU** [comment]
I just tested it and it works for me. I added  `"device.listen_addr": "::0",` to the top of my config file e.g. 

```json
{
    "device.listen_addr": "::0",
    "device.node_id": "opencanary-1",
    "git.enabled": true,
    "git.port" : 9418,
    "ftp.enabled": true,
    "ftp.port": 21,
    "ftp.banner": "FTP server ready",
    "http.banner": "Apache/2.2.22 (Ubuntu)",
    "http.enabled": true,
    "http.port": 80,
    ...
 ```

I'm using the [portpy3](https://github.com/thinkst/opencanary/tree/portpy3) branch, but I think it should work on the older branch too.

**Comment by jayjb** [comment]
Thanks for confirming @HybridAU ! TIL 👍

**Comment by Vincebye** [comment]
It worked.Thank you~
