### ISSUE TITLE
Cryptography version requirements conflict

### ISSUE THREAD

**Issue by chuck8773** [thinkst/opencanary#86]
When installing based on the current README, I encounter a conflict in the cryptography requirements.

Opencanary requires 2.6.1. rdpy requires something 2.8 or better.

pip install opencanary
	ERROR: pyopenssl 19.1.0 has requirement cryptography>=2.8, but you'll have cryptography 2.6.1 which is incompatible.
pip install rdpy
	ERROR: opencanary 0.5.4 has requirement cryptography==2.6.1, but you'll have cryptography 3.0 which is incompatible.

Everything seems to work fine regardless of which version is installed.

**Comment by HybridAU** [comment]
I believe the only place we use the cryptography library is in the [SSH module](https://github.com/thinkst/opencanary/blob/b6e092e423addc444041c1dc1712b22a4e4828c2/opencanary/modules/ssh.py#L17-L19). Looking at the [change log](https://cryptography.io/en/latest/changelog/#v3-1) from 2.5.0 up to version 3.1 it doesn't look like there are any changes that would cause an issue.

I'll do a few tests to confirm but it should be be bumping the [required version](https://github.com/thinkst/opencanary/blob/b6e092e423addc444041c1dc1712b22a4e4828c2/setup.py#L9) up to the latest.

**Comment by jayjb** [comment]
Thanks @HybridAU! (again!).

Let me know which version would make everything happy and ill bump it in the next version
