### ISSUE TITLE
Logging inconsistency

### ISSUE THREAD

**Issue by chuck8773** [thinkst/opencanary#87]
Some services log the dst_port with quotes, some log it without. This requires additional work in a SIEM to handle both cases.

"dst_port": 5060
"dst_port": 161
"dst_port": "21"
"dst_port": "3389"

**Comment by jayjb** [comment]
Hi @chuck8773,

Ah thats well spotted and definitely not expected. Would you mind telling me which services are doing which? And i can try get a fix in for this

**Comment by chuck8773** [comment]
Looks like the following services pulled from my config.
    "ftp.port": 21,
    "telnet.port": "23",
    "http.port": 80,
    "snmp.port": 161,
    "mssql.port":1433,
    "rdp.port": 3389,
    "redis.port": 6379,
    "tcpbanner_1.port": 8001,
5060

This may also be in the portscan detection.

**Comment by jayjb** [comment]
hi @chuck8773,

I have removed those quotes from the default config. Sorry that it caused inconvenience.
