### ISSUE TITLE
error " ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 2

### ISSUE THREAD

**Issue by lgflyman7611** [thinkst/opencanary#88]
Hi HybridAU，
     I'm working with the latest version of python3 based opencanary and saw the error when I tried to access the faked mysql service at 3306.

     I am not sure it is a bug or something else. Could do you please give a few advices? 

    Thank you! @HybridAU

**Comment by jayjb** [comment]
HI @lgflyman7611,

Would you mind telling me how you were trying to access the mysql service (and a little about your setup)? This way i can replicate the issue and try get a fix in. 

Thanks for reporting it btw

**Comment by lgflyman7611** [comment]
Yes. I  "apt-get install mysql-client" on ubuntu 1804 server, and access the service by typing "mysql -h <opencanary's IP> -u <any username> -p<any password>". Opencanary is still running on ubuntu 1804 server.

**Comment by lgflyman7611** [comment]
Hi @jayjb ,

Any updates?

**Comment by jayjb** [comment]
Hi @lgflyman7611,

Sorry for the delay. Currently I can trigger events on my opencanary (py2 and py3) using macos and ubuntu mysql client. 

Macos client version: `mysql  Ver 8.0.21 for osx10.15 on x86_64`
Ubuntu client version: `mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64)`

The error that you are reporting. Does that appear on the Opencanary side (using `opencanaryd --dev`) or is that message from the mysql client? 

I am trying to reproduce the issue so that we can try solve it.

**Comment by lgflyman7611** [comment]
I am not sure which side the issue is on. But also I tried accessing the service using SQLpro for MySQL app on macbook, turned out the same error. The following is how I install opencanary on ubuntu1804：

apt-get -y update 
apt-get -y install python3-dev python3-pip python3-scapy 
pip3 install opencanary

BTW, it is running on Python 3.8.2.

**Comment by jayjb** [comment]
Thanks for the additional info. When i get a moment today, Ill give that a test (running it in python 3.8)

**Comment by jayjb** [comment]
hi @lgflyman7611,

Confirmed I can replicate the issue. Its python3.8 specific. Ill take a go at fixing it tonight and let you know when it is fix. 

As an aside, if you run `opencanaryd --dev` if shows some debug logs. And when you try connect via mysql, you will see the actual issue.

**Comment by jayjb** [comment]
Hi @lgflyman7611,

Just pushed the fix and bumped the new version of opencanary to include some of the recent fixes that have gone into it. Let me know if it works for you.

**Comment by lgflyman7611** [comment]
Bravo!!! It worked! Thanks a lot! @jayjb

**Comment by jayjb** [comment]
Awesome, thanks @lgflyman7611!
