### ISSUE TITLE
cp: cannot stat ‘/usr/local/bin/../lib/python2.7/site-packages/opencanary/data/settings.json’: No such file or directory

### ISSUE THREAD

**Issue by leesoh** [thinkst/opencanary#9]
After the install, I ran opencanaryd --copyconfig and got this error: 

```
cp: cannot stat ‘/usr/local/bin/../lib/python2.7/site-packages/opencanary/data/settings.json’: No such file or directory
```

A quick search finds the file:

```
(venv)liam@ubuntu:/venv$ sudo find / -name 'settings.json'
/usr/local/lib/python2.7/dist-packages/opencanary/data/settings.json
```

**Comment by leesoh** [comment]
Manually copying that config to ~/.opencanary.conf and running --start generates the following
```
(venv)liam@ubuntu:/venv$ opencanaryd --start
[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Using config file: /home/liam/.opencanary.conf
WARNING: No route found for IPv6 destination :: (no default route?)
Invalid logging config
<type 'exceptions.ValueError'>
Unable to configure handler u'hpfeeds': global name 'hpfeeds' is not defined
```

**Comment by xistence** [comment]
I also encountered this issue, however I don't need HpFeeds for logging. If you just want other logging methods and want to quickly work around this issue you can remove the "hpfeeds" section from the "logger" section in the config. Just make it look something like this:

    "logger": {
        "class" : "PyLogger",
        "kwargs" : {
            "formatters": {
                "plain": {
                    "format": "%(message)s"
                }
            },
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                    "stream": "ext://sys.stdout"
                },
                "file": {
                    "class": "logging.FileHandler",
                    "filename": "/var/tmp/opencanary.log"
                },
                "syslog-unix": {
                    "class": "logging.handlers.SysLogHandler",
                    "address": ["localhost", 514],
                    "socktype": "ext://socket.SOCK_DGRAM"
                },
                "json-tcp": {
                    "class": "opencanary.logger.SocketJSONHandler",
                    "host": "127.0.0.1",
                    "port": 1514
                }
            }
        }
    },

**Comment by leesoh** [comment]
You're correct - I did a bit of work after opening the issue and got the same result. Was going to play with it a bit tonight to see if I could figure out why it was happening.

**Comment by leesoh** [comment]
Pull request in.

**Comment by thinkst** [comment]
Thanks for the pull request. 

For locating the config issue, we've pushed through a more general [fix](  https://github.com/thinkst/opencanary/commit/809b1836dee2d6d066ecf66d39f98e2ca3a14eea) to replace the original hardcoded path. Could you verify that it works in your environment?

For the second issue: we've removed hpfeeds from the default config and documented it instead. (See [809b183](https://github.com/thinkst/opencanary/commit/809b1836dee2d6d066ecf66d39f98e2ca3a14eea))

**Comment by leesoh** [comment]
Fix works!

**Comment by thinkst** [comment]
Thanks for the digging and testing on this @leesoh

**Comment by brendan004** [comment]
Hi guys. Thanks for all your input on opencanary. I've been knocking down one issue after the next b/c of it. I have removed hpfeeds and done all the things recommended here and I am running in to an issue that was mentioned but I don't see a fix (unless I'm just missing it). My error is now:
[root@localhost bin]# ./opencanaryd --start
[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Using config file: /root/.opencanary.conf
[-] Failed to decode json from /root/.opencanary.conf (Expecting property name: line 60 column 6 (char 1303))
[-] Failed to open /etc/opencanaryd/opencanary.conf for reading ([Errno 2] No such file or directory: '/etc/opencanaryd/opencanary.conf')
Error: config does not have 'logger' section

Any ideas?

**Comment by thinkst** [comment]
Hey @brendan004 

This looks like the json config file in `/root/.opencanary.conf` is malformed. Check you config file especially around line 60 as the error message suggests. (We often find that [jq](https://stedolan.github.io/jq/)  is very helpful for quickly verifying if a file is valid json.)

In future, please open a new ticket for new issues.
