### ISSUE TITLE
RDP service has not been added to fake

### ISSUE THREAD

**Issue by lgflyman7611** [thinkst/opencanary#90]
Hi @jayjb, 

Thanks again for fixing mysql service! Now I am testing the RDP service and found that it can be seen in opencanary.log like "Added xxx to fake". Tested it using Microsoft Remote Desktop app on Macbook, returned like
```
 " We couldn't connect to the remote PC. Make sure the PC is turned on and connected to the network, and that remote access is enabled.

Error code: 0x204
```
Python 3.8.2 remains the same, and here is how I install it:
```
apt-get -y install python3-dev python3-pip python3-scapy build-essential libssl-dev libffi-dev
pip3 install rdpy opencanary
```
there were three errors during installation:

```
ERROR: pyopenssl 19.1.0 has requirement cryptography>=2.8, but you'll have cryptography 2.5 which is incompatible.
ERROR: opencanary 0.5.5 has requirement pyasn1==0.4.5, but you'll have pyasn1 0.4.8 which is incompatible.
```
BTW, I did a search about the libary rdpy and found that update for it has been stopped since 2015, maybe it means something...

**Comment by jayjb** [comment]
Hi @lgflyman7611,

Ha! You found our neglected child 🙈 . We haven't developed on the RDP module for some time for a few reasons:
1. we feel we can do a better job of it
2. that said, RDP will take a good chunk of dev time (which we haven't assigned to it yet).

But we do plan on revisiting and redoing. Ill throw your name onto the list of "See, people will use it!" (its a longish list now).

**Comment by lgflyman7611** [comment]
😄  got it.

**Comment by belveruski** [comment]
> Hi @lgflyman7611,
> 
> Ha! You found our neglected child  . We haven't developed on the RDP module for some time for a few reasons:
> 
> 1. we feel we can do a better job of it
> 2. that said, RDP will take a good chunk of dev time (which we haven't assigned to it yet).
> 
> But we do plan on revisiting and redoing. Ill throw your name onto the list of "See, people will use it!" (its a longish list now).

Thanks for your job ! ;)
