### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by sgtwtf** [thinkst/opencanary#91]
I would love this even more if i could make the email alerts for startup events go to a different email than if an event was triggered.

Autorun prompt during setup or firstrun would be very useful.

**Comment by jayjb** [comment]
Hi @sgtwtf,

Ye its a known issue that we need to sort. We handle it on the commercial side by filtering logtypes (i.e. if log is from http about a login, then alert rather than alert on all logs). 

Ill add it to our update list (otherwise a PR is always welcome!)

**Comment by sgtwtf** [comment]
PR? Is that product request? Is there a place I can submit that for you?

**Comment by jayjb** [comment]
Hi @sgtwtf,

Ah sorry I shouldve explained it. I meant a "Pull Request". So all the code Opencanary uses is in this repository. If you find that you have some time and would like to contribute to this project, you can clone the Opencanary repository, make the changes that you would find useful, and submit them to me as a PR (Pull Request). 

Let me know if this is something you would be keen to try.
