### ISSUE TITLE
OpenCanary won't start

### ISSUE THREAD

**Issue by theonlyjedi** [thinkst/opencanary#94]
Trying to install Opencanary on Raspberry Pi4 running Ubuntu Server.  When entering
opencanaryd --start
getting back the following: 
** We hope you enjoy using OpenCanary. For more open source Canary goodness, head over to canarytokens.org. **
[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Failed to open /root/.opencanary.conf for reading ([Errno 2] No such file or directory: '/root/.opencanary.conf')
[-] Failed to open /etc/opencanaryd/opencanary.conf for reading ([Errno 2] No such file or directory: '/etc/opencanaryd/opencanary.conf')
Can't import RDP. Please ensure you have RDP installed.
Can't import SNMP. Please ensure you have Scapy installed.
Error: config does not have 'logger' section

**Comment by jayjb** [comment]
Hi @theonlyjedi,

Please would you mind pasting your opencanary config here. It sounds like the there is an issue there.

**Comment by theonlyjedi** [comment]
> Hi @theonlyjedi,
> 
> Please would you mind pasting your opencanary config here. It sounds like the there is an issue there.

Here's what I have
GNU nano 4.8                                       /home/ubuntu/.opencanary.conf                                                  
    "mysql.enabled": false,
    "mysql.port": 3306,
    "mysql.banner": "5.5.43-0ubuntu0.14.04.1",
    "ssh.enabled": false,
    "ssh.port": 22,
    "ssh.version": "SSH-2.0-OpenSSH_5.1p1 Debian-4",
    "redis.enabled": false,
    "redis.port": 6379,
    "rdp.enabled": false,
    "rdp.port": 3389,
    "sip.enabled": false,
    "sip.port": 5060,
    "snmp.enabled": false,
    "snmp.port": 161,
    "ntp.enabled": false,
    "ntp.port": "123",
    "tftp.enabled": false,
    "tftp.port": 69,
    "tcpbanner.maxnum":10,
    "tcpbanner.enabled": false,
    "tcpbanner_1.enabled": false,
    "tcpbanner_1.port": 8001,
    "tcpbanner_1.datareceivedbanner": "",
    "tcpbanner_1.initbanner": "",
    "tcpbanner_1.alertstring.enabled": false,
    "tcpbanner_1.alertstring": "",
    "tcpbanner_1.keep_alive.enabled": false,
    "tcpbanner_1.keep_alive_secret": "",
    "tcpbanner_1.keep_alive_probes": 11,
    "tcpbanner_1.keep_alive_interval":300,
    "tcpbanner_1.keep_alive_idle": 300,
    "telnet.enabled": false,
    "telnet.port": "23",
    "telnet.banner": "",
    "telnet.honeycreds": [
        {
            "username": "admin",
            "password": "$pbkdf2-sha512$19000$bG1NaY3xvjdGyBlj7N37Xw$dGrmBqqWa1okTCpN3QEmeo9j5DuV2u1EuVFD8Di0GxNiM64To5O/Y66f7UASvn>
        }
        {
            "username": "admin",
            "password": "admin1"
        }
    ],
    "mssql.enabled": false,
    "mssql.version": "2012",
    "mssql.port":1433,
    "vnc.enabled": false,
    "vnc.port":5000
}

**Comment by jayjb** [comment]
Hi @theonlyjedi,

You are missing the logger section of the Opencanary config. If you head over to [here](https://opencanary.readthedocs.io/en/latest/starting/configuration.html#logger-configuration), you will see the logger options.

**Comment by HybridAU** [comment]
Just looking at this, I think it might be the same issue as #99 because the logs start with 

```
[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Failed to open /root/.opencanary.conf for reading ([Errno 2] No such file or directory: '/root/.opencanary.conf')
[-] Failed to open /etc/opencanaryd/opencanary.conf for reading ([Errno 2] No such file or directory: '/etc/opencanaryd/opencanary.conf')
```
and @theonlyjedi says 

> Here's what I have
GNU nano 4.8 /home/ubuntu/.opencanary.conf

can you try moving your config file to `/etc/opencanaryd/opencanary.conf`

**Comment by jayjb** [comment]
Haha @HybridAU thats well spotted!  Thanks. Im closing this issue. Please reopen it if it is not resolved @theonlyjedi
