### ISSUE TITLE
Running opencanaryd error message command not found 

### ISSUE THREAD

**Issue by premsatha** [thinkst/opencanary#95]
I can find the command but it fails to execute. OS is Raspian lite latest August build.

**Comment by jayjb** [comment]
Hi @premsatha,

Could you give me a little more information? What error are you seeing? Which services are you trying to enable? What environment are you using?

**Comment by premsatha** [comment]
I have completed installation of open canary on pi3. Ran command opencanaryd —start. I get command opencanaryd not found. Did ls - ll the command is there with rwx

**Comment by jayjb** [comment]
Hi @premsatha,

Thanks for the additional info (although there isnt much to go on here).

Would you mind pasting your commands and output? How did you install Opencanary? If you installed it using `pip install opencanary` then you would need to make sure that you are in the same environment that you installed it into. 

You can check that your python virtual environment has your opencanaryd by checking your current `PATH` variable using `echo $PATH` and ensuring that your python virtual environment is in that `PATH` variable.

Once you have confirmed that; you can check the virtual environment, with `ls -lah <path to enviroment>/bin` and see if it has `opencanaryd` in there.

**Comment by premsatha** [comment]
I installed opencanary from source. I did not install the virtual environment. The os I am using is raspian lite. 
![2605EAAD-A1D7-4821-A732-A7FBDFDE3586](https://user-images.githubusercontent.com/15081114/91778110-257abd00-ec24-11ea-9381-32243f7e16d4.png)

**Comment by jayjb** [comment]
Hi @premsatha,

Did @nodauf comment help? Let me know.

**Comment by premsatha** [comment]
Hi @jayjb unfortunately it did not. I encountered more errors. Left it for now, did not have time to analyze the errors.

**Comment by jayjb** [comment]
Hi @premsatha,

Sorry to hear that. If you send through the errors you are experiencing, i can try help debug what you are seeing.

**Comment by ldwedari** [comment]
I had the same issue.  The opencanaryd executable file is added to the /home/pi/.local/bin folder which is not part of $PATH. 
Append the line: 
export PATH="/home/pi/.local/bin:$PATH"
to your ~/.bashrc file. That should fix it.

**Comment by jayjb** [comment]
Thanks @ldwedari. Ill add these comments to the FAQ
