### ISSUE TITLE
Can't import RDP

### ISSUE THREAD

**Issue by kmc56** [thinkst/opencanary#97]
Hi, 

I've been struggling to get opencanary to import RDP when starting the service. 

I have rdpy installed and am using RHEL 8 VM. I've tried some fresh installs and still no joy. 

Is there a compatibility issue with RHEL? or anything blatantly obvious that I may be missing? Happy to provide more info !

Also when installing rdpy it shows this error which says the version of opencanary  (0.5.5) is incompatible with the cryptography:
![image](https://user-images.githubusercontent.com/71138077/92936603-2db3d300-f442-11ea-9390-a291f6affae2.png)

But the version installed shows 1.0

Thanks,
K

**Comment by kmc56** [comment]
I read issue #90 previously, is this related or is this module not in a state for usage currently?

**Comment by jayjb** [comment]
Hi @kmc56,

Sorry for the delayed response. Currently, the RDP module hasn't been worked on for some time. We should make a note on the home page. So to be clear, the module isn't in a usage state currently. It needs to be updated (to python3 and in functionality). 

Ill add your name to the list and see if we can get some dev time for it.

**Comment by kmc56** [comment]
Awesome, thanks for the reply! Looking forward to working with it in the future if it gets the dev time.

**Comment by jayjb** [comment]
@kmc56 Ill let you know when it does. Thanks for trying out Opencanary

**Comment by tackynugget** [comment]
@jayjb thanks for your consideration of this issue.

I stumbled on this issue as well as #70 and was wondering whether the library in [PyRDP](https://github.com/GoSecure/pyrdp) might help restore this functionality? RDP is a popular attack vector and its absence in a honeypot in a Windows-based environment could make the opencanary stand out.
