### ISSUE TITLE
Error: config does not have 'logger' section

### ISSUE THREAD

**Issue by YouAllHaveZoidberg** [thinkst/opencanary#99]
I searched and saw a few of these errors posted, but none of the solutions worked for me.  I used https://www.michaelrinderle.com/2020/06/08/sticking-an-attacker-in-a-honeypot-with-opencanary/ guide for the setup and config. 

I'm seeing Error: config does not have 'logger' section, and the canary doesn't seem to be starting. 

![1](https://user-images.githubusercontent.com/71720692/93912414-c0216580-fcd1-11ea-9977-d119fd297e40.png)

The only part of the config I modified was to add SMTP. 

![2](https://user-images.githubusercontent.com/71720692/93912547-e47d4200-fcd1-11ea-8fc8-332e702aac16.png)

Any suggestions? I thought this would be very easy to setup, but I can't get past this.

**Comment by jayjb** [comment]
Hi @YouAllHaveZoidberg,

We have some documentation on this section over [here](https://opencanary.readthedocs.io/en/latest/starting/configuration.html#logger-configuration). Hopefully it helps. Just from eyeballing your logger configuration I dont see anything blatantly broken. It may be a case of a mismatch of `{}` brackets.

**Comment by YouAllHaveZoidberg** [comment]
Thanks for the reply. I checked that out while I was going through the config to verify against the guide I was following, and I just now checked the braces and they're proper. I found how to export the config. It's all default except for the SMTP addition. I also regenerated the config without modifying it and got the same error.

{
    "device.node_id": "opencanary-1",
    "git.enabled": false,
    "git.port" : 9418,
    "ftp.enabled": true,
    "ftp.port": 21,
    "ftp.banner": "FTP server ready",
    "http.banner": "Apache/2.2.22 (Ubuntu)",
    "http.enabled": false,
    "http.port": 80,
    "http.skin": "nasLogin",
    "http.skin.list": [
        {
            "desc": "Plain HTML Login",
            "name": "basicLogin"
        },
        {
            "desc": "Synology NAS Login",
            "name": "nasLogin"
        }
    ],
    "httpproxy.enabled" : false,
    "httpproxy.port": 8080,
    "httpproxy.skin": "squid",
    "httproxy.skin.list": [
        {
            "desc": "Squid",
            "name": "squid"
        },
        {
            "desc": "Microsoft ISA Server Web Proxy",
            "name": "ms-isa"
        }
    ],
    "logger": {
        "class": "PyLogger",
        "kwargs": {
            "formatters": {
                "plain": {
                    "format": "%(message)s"
                }
            },
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                    "stream": "ext://sys.stdout"
                },
                "file": {
                    "class": "logging.FileHandler",
                    "filename": "/var/tmp/opencanary.log"
                },
		"SMTP": {
		    "class": "logging.handlers.SMTPHandler",
		    "mailhost": ["censored.server.thing", 25],
		    "fromaddr": "censored@domain.thing",
		    "toaddrs": ["censored@domain.thing"],
		    "subject": "OpenCanary Operations Alert",
		    "secure": []
		}    
            }
        }
    },
    "portscan.enabled": false,
    "portscan.logfile":"/var/log/kern.log",
    "portscan.synrate": 5,
    "portscan.nmaposrate": 5,
    "portscan.lorate": 3,
    "smb.auditfile": "/var/log/samba-audit.log",
    "smb.enabled": false,
    "mysql.enabled": false,
    "mysql.port": 3306,
    "mysql.banner": "5.5.43-0ubuntu0.14.04.1",
    "ssh.enabled": false,
    "ssh.port": 22,
    "ssh.version": "SSH-2.0-OpenSSH_5.1p1 Debian-4",
    "redis.enabled": false,
    "redis.port": 6379,
    "rdp.enabled": false,
    "rdp.port": 3389,
    "sip.enabled": false,
    "sip.port": 5060,
    "snmp.enabled": false,
    "snmp.port": 161,
    "ntp.enabled": false,
    "ntp.port": "123",
    "tftp.enabled": false,
    "tftp.port": 69,
    "tcpbanner.maxnum":10,
    "tcpbanner.enabled": false,
    "tcpbanner_1.enabled": false,
    "tcpbanner_1.port": 8001,
    "tcpbanner_1.datareceivedbanner": "",
    "tcpbanner_1.initbanner": "",
    "tcpbanner_1.alertstring.enabled": false,
    "tcpbanner_1.alertstring": "",
    "tcpbanner_1.keep_alive.enabled": false,
    "tcpbanner_1.keep_alive_secret": "",
    "tcpbanner_1.keep_alive_probes": 11,
    "tcpbanner_1.keep_alive_interval":300,
    "tcpbanner_1.keep_alive_idle": 300,
    "telnet.enabled": false,
    "telnet.port": "23",
    "telnet.banner": "",
    "telnet.honeycreds": [
        {
            "username": "admin",
            "password": "$pbkdf2-sha512$19000$bG1NaY3xvjdGyBlj7N37Xw$dGrmBqqWa1okTCpN3QEmeo9j5DuV2u1EuVFD8Di0GxNiM64To5O/Y66f7UASvnQr8.LCzqTm6awC8Kj/aGKvwA"
        },
        {
            "username": "admin",
            "password": "admin1"
        }
    ],
    "mssql.enabled": false,
    "mssql.version": "2012",
    "mssql.port":1433,
    "vnc.enabled": false,
    "vnc.port":5000
}

**Comment by YouAllHaveZoidberg** [comment]
Does anyone have a guide they can share that they used for the config? Or, is there a better alternative than Ubuntu that works?

**Comment by HybridAU** [comment]
Can you try moving your config file to `/etc/opencanaryd/opencanary.conf` and see if that works?

I've been having a bit of a play with this and I think I might have found a bug that would be giving you this error. 

It seems like if we can't find the config file, `getLogger` is the first thing that's called that [needs a config](https://github.com/thinkst/opencanary/blob/fea6e084ef718d0ad09d8e3114631b80aa9663d5/opencanary/logger.py#L20) file, and if the config is `None` it throws the error `Error: config does not have 'logger' section`

I seems like if the config file is in the home directory `~/.opencanary.conf` sometimes we can't read it. I'm still trying to track down exactly why, and once I do I'll make a PR. But for now see if moving the location of your config file works.

**Comment by YouAllHaveZoidberg** [comment]
That worked! Thanks for your help.

**Comment by jayjb** [comment]
Thanks @HybridAU! Its a good find (and fix!).

**Comment by xx-zhang** [comment]
# error log 
```
[root@localhost opencanary-master]# opencanaryd --start
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "/usr/local/bin/opencanary.tac", line 4, in <module>
    __import__('pkg_resources').run_script('opencanary==0.5.6', 'opencanary.tac')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 651, in run_script
    name = ns['__name__']
builtins.KeyError: '__name__'


Failed to load application: '__name__'

```

## opencanary.conf 
- as same as later

**Comment by jayjb** [comment]
Hi @xx-zhang,

Sorry you hitting this issue. Did you install your Opencanary using `pip install opencanary`? or did you clone the git repo and use `pip install .`?

**Comment by andy778** [comment]
I had same problem with logger error and the problem for me was that it didn't find config file in home directory when it had the leading dot.
/home/ubuntu/.opencanary.conf -> /home/ubuntu/opencanary.conf [OK]

I installed this on raspberry with Ubuntu 20.10 and 32 bit
pip install opencanary

**Comment by casten** [comment]
> Hi @xx-zhang,
> 
> Sorry you hitting this issue. Did you install your Opencanary using `pip install opencanary`? or did you clone the git repo and use `pip install .`?

I am encountering this as well.  I tried installing using pip as well as from /dist after cloning and building.

**Comment by jayjb** [comment]
Please open a new issue with details of the issue so we can tackle it.
